/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Image;
import java.awt.PopupMenu;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author One For All
 */
public class FormPelanggan extends javax.swing.JPanel {
    private final Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form FormPelanggan
     */
    public FormPelanggan() {
        initComponents();
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();
        panelForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        tNik = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        tTelp = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAlamat = new javax.swing.JTextArea();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnPilihFoto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ktp = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        tCari = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1299, 800));

        kGradientPanel1.setkEndColor(new java.awt.Color(98, 215, 196));
        kGradientPanel1.setkGradientFocus(2000);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 87, 64));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelPelanggan.setBackground(new java.awt.Color(1, 135, 100));
        tabelPelanggan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPelanggan);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 730, 370));

        panelForm.setBackground(new java.awt.Color(0, 71, 67));
        panelForm.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Data Pelanggan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 188, 97));
        jLabel1.setText("E-mail");
        panelForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 188, 97));
        jLabel2.setText(":");
        panelForm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 10, -1));

        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(249, 188, 97));
        jLabel3.setText("Nama");
        panelForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(249, 188, 97));
        jLabel4.setText("Alamat");
        panelForm.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(249, 188, 97));
        jLabel5.setText("No Telpon");
        panelForm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        tEmail.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEmailActionPerformed(evt);
            }
        });
        panelForm.add(tEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 200, -1));

        tNik.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tNik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNikActionPerformed(evt);
            }
        });
        panelForm.add(tNik, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 150, -1));

        tNama.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaActionPerformed(evt);
            }
        });
        panelForm.add(tNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 200, -1));

        tTelp.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTelpActionPerformed(evt);
            }
        });
        panelForm.add(tTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 200, -1));

        tAlamat.setColumns(20);
        tAlamat.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tAlamat.setRows(5);
        jScrollPane2.setViewportView(tAlamat);

        panelForm.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 200, 100));

        btnClear.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh26.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.setInheritsPopupMenu(true);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        panelForm.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 100, 30));

        btnDelete.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trash.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setInheritsPopupMenu(true);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        panelForm.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 100, 30));

        btnEdit.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit_f2.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setInheritsPopupMenu(true);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        panelForm.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 100, 30));

        btnSave.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/save-16x16i.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setInheritsPopupMenu(true);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panelForm.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 100, 30));

        btnPilihFoto.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnPilihFoto.setIcon(new javax.swing.ImageIcon("C:\\Users\\bamba\\Downloads\\icons8-choose-16.png")); // NOI18N
        btnPilihFoto.setText("File");
        btnPilihFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihFotoActionPerformed(evt);
            }
        });
        panelForm.add(btnPilihFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 80, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ktp, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ktp, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        panelForm.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 280, 150));

        jLabel8.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(249, 188, 97));
        jLabel8.setText("NIK");
        panelForm.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(249, 188, 97));
        jLabel9.setText(":");
        panelForm.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 10, -1));

        jLabel10.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(249, 188, 97));
        jLabel10.setText(":");
        panelForm.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 10, -1));

        jLabel11.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(249, 188, 97));
        jLabel11.setText(":");
        panelForm.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 10, -1));

        jLabel12.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(249, 188, 97));
        jLabel12.setText(":");
        panelForm.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 10, -1));

        kGradientPanel1.add(panelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 400, 610));

        btnSearch.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cari.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setInheritsPopupMenu(true);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 110, 30));

        tCari.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        tCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCariActionPerformed(evt);
            }
        });
        kGradientPanel1.add(tCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 190, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/customers-icon-12 edit.png"))); // NOI18N
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 330, 300));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bgkayu.jpg"))); // NOI18N
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1337, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    protected void aktif(){
        tNik.setEnabled(true);
        tNama.setEnabled(true);
        tAlamat.setEnabled(true);
        tTelp.setEnabled(true);
        tEmail.setEnabled(true);
        tNik.requestFocus();
    }
    
    protected void kosong(){
        ktp.setIcon(null);
        tNik.setText("");
        tNama.setText("");
        tAlamat.setText("");
        tTelp.setText("");
        tEmail.setText("");
    }
    
    protected void datatable(){
        Object[] Baris={"No Induk","Nama Pelanggan","Alamat","No Telpon","Email"};
        tabmode = new DefaultTableModel(null,Baris);
        tabelPelanggan.setModel(tabmode);
        String sql="SELECT * FROM pelanggan WHERE nik LIKE '%"+tCari.getText()+"%' "
                + "OR nama LIKE '%"+tCari.getText()+"%' "
                + "OR alamat LIKE '%"+tCari.getText()+"%' "
                + "OR telp LIKE '%"+tCari.getText()+"%' "
                + "OR email LIKE '%"+tCari.getText()+"%'";
        try{
            java.sql.Statement stat=conn.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                String a=hasil.getString("nik");
                String b=hasil.getString("nama");
                String c=hasil.getString("alamat");
                String d=hasil.getString("telp");
                String e=hasil.getString("email");
                String[] data={a,b,c,d,e};
                tabmode.addRow(data);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Tidak Bisa Menampilkan Tabel" + e);
        }
    }
    
    private String filename;
    
    private void tEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEmailActionPerformed

    private void tNikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNikActionPerformed

    private void tNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaActionPerformed

    private void tTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTelpActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        kosong();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int ok = JOptionPane.showConfirmDialog(null,"Hapus ?","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok==0){
            String sql="DELETE FROM pelanggan WHERE nik='"+tNik.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");
                kosong();
                tNik.requestFocus();
                datatable();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Data Gagal Dihapus"+e);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try{
            String sql = "UPDATE pelanggan SET nama=?,alamat=?,telp=?,email=?,foto_ktp=? WHERE nik=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1,tNama.getText());
            stat.setString(2,tAlamat.getText());
            stat.setString(3,tTelp.getText());
            stat.setString(4,tEmail.getText());
            String newpath = "src/upload";
            File directory = new File(newpath);
            if(!directory.exists()){
                directory.mkdirs();
            }
            File fileawal = null;
            File fileakhir = null;
            String ext = this.filename.substring(filename.lastIndexOf('.')+1);
            fileawal = new File(filename);
            fileakhir = new File(newpath+"/"+tNik.getText()+"(1)."+ext);
            stat.setString(5,fileakhir.toString());
            stat.setString(6,tNik.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            Files.copy(fileawal.toPath(), fileakhir.toPath());
            kosong();
            tNik.requestFocus();
            datatable();
        }catch(SQLException e){ 
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
        } catch (IOException ex) {
            Logger.getLogger(FormPelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String sql = "INSERT INTO pelanggan VALUES(?,?,?,?,?,?)";
        try{          
            String newpath = "src/upload";
            File directory = new File(newpath);
            if(!directory.exists()){
                directory.mkdirs();
            }
            File fileawal = null;
            File fileakhir = null;
            String ext = this.filename.substring(filename.lastIndexOf('.')+1);
            fileawal = new File(filename);
            fileakhir = new File(newpath+"/"+tNik.getText()+"."+ext);     
        PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, tNik.getText());
        stat.setString(2, tNama.getText());
        stat.setString(3, tAlamat.getText());
        stat.setString(4, tTelp.getText());
        stat.setString(5, tEmail.getText());
        stat.setString(6, fileakhir.toString());
        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
        Files.copy(fileawal.toPath(), fileakhir.toPath());
        kosong();
        tNik.requestFocus();
        datatable();
        }catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e); 
        }catch(IOException ex) {
              Logger.getLogger(FormPelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    public void foto(String a){
        String sql = "SELECT foto_ktp FROM pelanggan Where nik = '"+a+"'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String foto = hasil.getString("foto_ktp");
                ImageIcon icon = new ImageIcon(foto);
                Image img = icon.getImage().getScaledInstance(ktp.getWidth(), ktp.getHeight(), Image.SCALE_DEFAULT);
                ImageIcon ic = new ImageIcon(img);
                ktp.setIcon(ic);
            }
        }catch(Exception e) {
            
        }
    }
    
    private void tabelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPelangganMouseClicked
        int bar = tabelPelanggan.getSelectedRow();
        String a = tabmode.getValueAt(bar,0).toString();
        String b = tabmode.getValueAt(bar,1).toString();
        String c = tabmode.getValueAt(bar,2).toString();
        String d = tabmode.getValueAt(bar,3).toString();
        String e = tabmode.getValueAt(bar,4).toString();
        foto(a);
        tNik.setText(a);
        tNama.setText(b);
        tAlamat.setText(c);
        tTelp.setText(d);
        tEmail.setText(e);
    }//GEN-LAST:event_tabelPelangganMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        datatable();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCariActionPerformed

    private void btnPilihFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihFotoActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(f.toString());
            Image img = icon.getImage().getScaledInstance(ktp.getWidth(), ktp.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon ic = new ImageIcon(img);
            ktp.setIcon(ic);
            filename = f.getAbsolutePath();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnPilihFotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnPilihFoto;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel ktp;
    private javax.swing.JPanel panelForm;
    private javax.swing.JTextArea tAlamat;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNik;
    private javax.swing.JTextField tTelp;
    private javax.swing.JTable tabelPelanggan;
    // End of variables declaration//GEN-END:variables

    PopupMenu setLayout(int i, int i0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
