/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;


/**
 *
 * @author One For All
 */

public class Form extends javax.swing.JFrame {
    //private final JPanel pnl1;
    /**
     * Creates new form MainMenu
     */
    int mousepX ;
    int mousepY ;
    boolean a=true;
    
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        Icon = new javax.swing.JPanel();
        ButtonClose = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        ButtonMax = new javax.swing.JPanel();
        maximize = new javax.swing.JLabel();
        ButtonMin = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        LineHideMenu = new javax.swing.JPanel();
        HideMenu = new javax.swing.JPanel();
        buttonhidemenu = new javax.swing.JLabel();
        LineLogout = new javax.swing.JPanel();
        Logout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        MenuHide = new javax.swing.JPanel();
        btnPelanggan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnPinjam = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnMobil = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnTentang = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnPengembalian = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnLaporan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        main_panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1320, 800));
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(1, 135, 100));
        Header.setPreferredSize(new java.awt.Dimension(1500, 35));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new java.awt.BorderLayout());

        Icon.setBackground(new java.awt.Color(0, 0, 255));
        Icon.setPreferredSize(new java.awt.Dimension(120, 50));
        Icon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonClose.setBackground(new java.awt.Color(1, 135, 100));
        ButtonClose.setPreferredSize(new java.awt.Dimension(40, 35));
        ButtonClose.setLayout(new java.awt.BorderLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/close-24.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        ButtonClose.add(close, java.awt.BorderLayout.CENTER);

        Icon.add(ButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        ButtonMax.setBackground(new java.awt.Color(1, 135, 100));
        ButtonMax.setPreferredSize(new java.awt.Dimension(40, 35));
        ButtonMax.setLayout(new java.awt.BorderLayout());

        maximize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Max 24px.png"))); // NOI18N
        maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maximizeMouseExited(evt);
            }
        });
        ButtonMax.add(maximize, java.awt.BorderLayout.CENTER);

        Icon.add(ButtonMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        ButtonMin.setBackground(new java.awt.Color(1, 135, 100));
        ButtonMin.setPreferredSize(new java.awt.Dimension(40, 35));
        ButtonMin.setLayout(new java.awt.BorderLayout());

        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Substract 24px.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        ButtonMin.add(minimize, java.awt.BorderLayout.CENTER);

        Icon.add(ButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Header.add(Icon, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        menu.setBackground(new java.awt.Color(51, 51, 255));
        menu.setPreferredSize(new java.awt.Dimension(50, 450));
        menu.setLayout(new java.awt.BorderLayout());

        MenuIcon.setBackground(new java.awt.Color(1, 135, 100));
        MenuIcon.setMinimumSize(new java.awt.Dimension(210, 779));
        MenuIcon.setPreferredSize(new java.awt.Dimension(210, 779));
        MenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LineHideMenu.setBackground(new java.awt.Color(1, 135, 100));
        LineHideMenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout LineHideMenuLayout = new javax.swing.GroupLayout(LineHideMenu);
        LineHideMenu.setLayout(LineHideMenuLayout);
        LineHideMenuLayout.setHorizontalGroup(
            LineHideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        LineHideMenuLayout.setVerticalGroup(
            LineHideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(LineHideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        HideMenu.setBackground(new java.awt.Color(1, 135, 100));
        HideMenu.setPreferredSize(new java.awt.Dimension(50, 50));
        HideMenu.setLayout(new java.awt.BorderLayout());

        buttonhidemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhidemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Menu-Hamburger 45px.png"))); // NOI18N
        buttonhidemenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonhidemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseExited(evt);
            }
        });
        HideMenu.add(buttonhidemenu, java.awt.BorderLayout.CENTER);

        MenuIcon.add(HideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, -1));

        LineLogout.setBackground(new java.awt.Color(1, 135, 100));
        LineLogout.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout LineLogoutLayout = new javax.swing.GroupLayout(LineLogout);
        LineLogout.setLayout(LineLogoutLayout);
        LineLogoutLayout.setHorizontalGroup(
            LineLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        LineLogoutLayout.setVerticalGroup(
            LineLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(LineLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, -1));

        Logout.setBackground(new java.awt.Color(1, 135, 100));
        Logout.setPreferredSize(new java.awt.Dimension(50, 50));
        Logout.setLayout(new java.awt.BorderLayout());

        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-shutdown-45.png"))); // NOI18N
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogoutMousePressed(evt);
            }
        });
        Logout.add(btnLogout, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, -1));

        MenuHide.setBackground(new java.awt.Color(1, 135, 100));
        MenuHide.setMinimumSize(new java.awt.Dimension(50, 800));
        MenuHide.setPreferredSize(new java.awt.Dimension(50, 800));

        javax.swing.GroupLayout MenuHideLayout = new javax.swing.GroupLayout(MenuHide);
        MenuHide.setLayout(MenuHideLayout);
        MenuHideLayout.setHorizontalGroup(
            MenuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        MenuHideLayout.setVerticalGroup(
            MenuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        MenuIcon.add(MenuHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, 800));

        btnPelanggan.setBackground(new java.awt.Color(1, 71, 67));
        btnPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPelangganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPelangganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPelangganMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(249, 188, 97));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/customer-icon-40px.png"))); // NOI18N
        jLabel7.setText("Pelanggan");

        javax.swing.GroupLayout btnPelangganLayout = new javax.swing.GroupLayout(btnPelanggan);
        btnPelanggan.setLayout(btnPelangganLayout);
        btnPelangganLayout.setHorizontalGroup(
            btnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPelangganLayout.setVerticalGroup(
            btnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPelangganLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuIcon.add(btnPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 160, 50));

        btnPinjam.setBackground(new java.awt.Color(1, 71, 67));
        btnPinjam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPinjamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPinjamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPinjamMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(249, 188, 97));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/loan 40px.png"))); // NOI18N
        jLabel4.setText("Pinjam Mobil");

        javax.swing.GroupLayout btnPinjamLayout = new javax.swing.GroupLayout(btnPinjam);
        btnPinjam.setLayout(btnPinjamLayout);
        btnPinjamLayout.setHorizontalGroup(
            btnPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPinjamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnPinjamLayout.setVerticalGroup(
            btnPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPinjamLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuIcon.add(btnPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 170, 50));

        btnMobil.setBackground(new java.awt.Color(1, 71, 67));
        btnMobil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMobilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMobilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMobilMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 188, 97));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cars-icon-40.png"))); // NOI18N
        jLabel2.setText("Mobil");

        javax.swing.GroupLayout btnMobilLayout = new javax.swing.GroupLayout(btnMobil);
        btnMobil.setLayout(btnMobilLayout);
        btnMobilLayout.setHorizontalGroup(
            btnMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMobilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnMobilLayout.setVerticalGroup(
            btnMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMobilLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuIcon.add(btnMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 170, -1));

        btnTentang.setBackground(new java.awt.Color(1, 71, 67));
        btnTentang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTentangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTentangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTentangMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(249, 188, 97));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-driver-48.png"))); // NOI18N
        jLabel5.setText("Supir");

        javax.swing.GroupLayout btnTentangLayout = new javax.swing.GroupLayout(btnTentang);
        btnTentang.setLayout(btnTentangLayout);
        btnTentangLayout.setHorizontalGroup(
            btnTentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTentangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnTentangLayout.setVerticalGroup(
            btnTentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTentangLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuIcon.add(btnTentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 170, 50));

        btnPengembalian.setBackground(new java.awt.Color(1, 71, 67));
        btnPengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPengembalianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPengembalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPengembalianMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(249, 188, 97));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/car-loan 40px.png"))); // NOI18N
        jLabel6.setText("Pengembalian");

        javax.swing.GroupLayout btnPengembalianLayout = new javax.swing.GroupLayout(btnPengembalian);
        btnPengembalian.setLayout(btnPengembalianLayout);
        btnPengembalianLayout.setHorizontalGroup(
            btnPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPengembalianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnPengembalianLayout.setVerticalGroup(
            btnPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPengembalianLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuIcon.add(btnPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 160, -1));

        btnLaporan.setBackground(new java.awt.Color(1, 71, 67));
        btnLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaporanMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 188, 97));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/report 40px.png"))); // NOI18N
        jLabel1.setText("Laporan");

        javax.swing.GroupLayout btnLaporanLayout = new javax.swing.GroupLayout(btnLaporan);
        btnLaporan.setLayout(btnLaporanLayout);
        btnLaporanLayout.setHorizontalGroup(
            btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLaporanLayout.setVerticalGroup(
            btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        MenuIcon.add(btnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 170, -1));

        menu.add(MenuIcon, java.awt.BorderLayout.LINE_START);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        main_panel.setBackground(new java.awt.Color(0, 0, 0));
        main_panel.setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        main_panel.add(jPanel1, "card2");

        getContentPane().add(main_panel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(999, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    

    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
        if(numberbool == 1){
            h1.setBackground(new Color(1,71,67));
            h2.setBackground(new Color(1,135,100));
        }
        else{
            h1.setBackground(new Color(1,135,100));
            h2.setBackground(new Color(1,71,67));
        }
    }
    
    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button){
        if(dashboard == true){
            menushowhide.setPreferredSize(new Dimension(210, menushowhide.getHeight()));
            changeimage(button, "/Icon/Double-left 45px.png" ); 
            changecolor(MenuIcon, new Color(1,71,67));
        }
        else{
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
            changeimage(button, "/Icon/Menu-Hamburger 45px.png" );
            changecolor(HideMenu, new Color(1,135,100));
            changecolor(MenuIcon, new Color(1,135,100));
        }
    }
    
    public void cratepanel(JPanel menushowside, boolean dashboard){
        if (dashboard == true){
            menushowside.setPreferredSize(new Dimension(50,menushowside.getHeight()));
        }
        else{
            menushowside.setPreferredSize(new Dimension(210,menushowside.getHeight()));
        }
    }
    
    public void changeimage(JLabel button, String resourcheimg){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
        button.setIcon(aimg);
    }
    
    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        changecolor(ButtonClose, new Color(100,135,100));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        changecolor(ButtonClose, new Color(1,135,100));
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void maximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseEntered
        changecolor(ButtonMax, new Color(100,135,100));
    }//GEN-LAST:event_maximizeMouseEntered

    private void maximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseExited
        changecolor(ButtonMax, new Color(1,135,100));
    }//GEN-LAST:event_maximizeMouseExited

    private void maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseClicked
        if(this.getExtendedState()!= Form.MAXIMIZED_BOTH){
            this.setExtendedState(Form.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(Form.NORMAL);
        }
    }//GEN-LAST:event_maximizeMouseClicked

    
    private void buttonhidemenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseEntered
        changecolor(LineHideMenu, new Color(249, 188, 97));
    }//GEN-LAST:event_buttonhidemenuMouseEntered

    private void buttonhidemenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseExited
        changecolor(LineHideMenu, new Color(1,135,100));
    }//GEN-LAST:event_buttonhidemenuMouseExited

    private void buttonhidemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseClicked
        clickmenu(HideMenu, Logout, 1);
        
        // buat method untuk menampilkan menu
        if(a==true){
            hideshow(menu, a, buttonhidemenu);
            SwingUtilities.updateComponentTreeUI(this);
            // buat method untuk mengganti gambar
            a=false;
        }
        else{
            hideshow(menu, a, buttonhidemenu);
            SwingUtilities.updateComponentTreeUI(this);
            a=true;
        }
        
    }//GEN-LAST:event_buttonhidemenuMouseClicked

    
    
    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        changecolor(LineLogout, new Color(247, 2, 2));
    }//GEN-LAST:event_btnLogoutMouseEntered
    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        changecolor(LineLogout, new Color(1,135,100));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMousePressed

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        login log = new login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int koordinatX = evt.getXOnScreen();
        int koordinatY = evt.getYOnScreen();
        
        this.setLocation(koordinatX-mousepX, koordinatY-mousepY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        changecolor(ButtonMin, new Color(100,135,100));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        changecolor(ButtonMin, new Color(1,135,100));
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void btnPelangganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPelangganMouseEntered
        // TODO add your handling code here:
        changecolor(btnPelanggan, new Color(1,135,100));
    }//GEN-LAST:event_btnPelangganMouseEntered

    private void btnPelangganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPelangganMouseExited
        // TODO add your handling code here:
        changecolor(btnPelanggan, new Color(1,71,67));
    }//GEN-LAST:event_btnPelangganMouseExited

    private void btnPinjamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPinjamMouseEntered
        // TODO add your handling code here:
        changecolor(btnPinjam, new Color(1,135,100));
    }//GEN-LAST:event_btnPinjamMouseEntered

    private void btnPinjamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPinjamMouseExited
        // TODO add your handling code here:
        changecolor(btnPinjam, new Color(1,71,67));
    }//GEN-LAST:event_btnPinjamMouseExited

    private void btnMobilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMobilMouseEntered
        // TODO add your handling code here:
        changecolor(btnMobil, new Color(1,135,100));
    }//GEN-LAST:event_btnMobilMouseEntered

    private void btnMobilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMobilMouseExited
        // TODO add your handling code here:
        changecolor(btnMobil, new Color(1,71,67));
    }//GEN-LAST:event_btnMobilMouseExited

    private void btnTentangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTentangMouseEntered
        // TODO add your handling code here:
        changecolor(btnTentang, new Color(1,135,100));
    }//GEN-LAST:event_btnTentangMouseEntered

    private void btnTentangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTentangMouseExited
        // TODO add your handling code here:
        changecolor(btnTentang, new Color(1,71,67));
    }//GEN-LAST:event_btnTentangMouseExited

    private void btnPengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengembalianMouseEntered
        // TODO add your handling code here:
        changecolor(btnPengembalian, new Color(1,135,100));
    }//GEN-LAST:event_btnPengembalianMouseEntered

    private void btnPengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengembalianMouseExited
        // TODO add your handling code here:
        changecolor(btnPengembalian, new Color(1,71,67));
    }//GEN-LAST:event_btnPengembalianMouseExited

    private void btnLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseEntered
        // TODO add your handling code here:
        changecolor(btnLaporan, new Color(1,135,100));
    }//GEN-LAST:event_btnLaporanMouseEntered

    private void btnLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseExited
        // TODO add your handling code here:
        changecolor(btnLaporan, new Color(1,71,67));
    }//GEN-LAST:event_btnLaporanMouseExited

//    private void cratePanel(){
//        this.cratePanel();
//        this.setVisible(true);
//    }
    
    private void btnPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPelangganMouseClicked
        main_panel.removeAll();
        main_panel.repaint();
        FormPelanggan fp = new FormPelanggan();
        fp.setVisible(true);
        main_panel.add(fp);
        main_panel.revalidate();
    }//GEN-LAST:event_btnPelangganMouseClicked

    private void btnPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPinjamMouseClicked
        main_panel.removeAll();
        main_panel.repaint();
        FormTransaksi ft = new FormTransaksi();
        ft.setVisible(true);
        main_panel.add(ft);
        main_panel.revalidate();
    }//GEN-LAST:event_btnPinjamMouseClicked

    private void btnMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMobilMouseClicked
        main_panel.removeAll();
        main_panel.repaint();
        FormMobil fm = new FormMobil();
        fm.setVisible(true);
        main_panel.add(fm);
        main_panel.revalidate();
    }//GEN-LAST:event_btnMobilMouseClicked

    private void btnPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengembalianMouseClicked
        main_panel.removeAll();
        main_panel.repaint();
        FormPengembalian fk = new FormPengembalian();
        fk.setVisible(true);
        main_panel.add(fk);
        main_panel.revalidate();
    }//GEN-LAST:event_btnPengembalianMouseClicked

    private void btnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseClicked
        FormLaporan fl = new FormLaporan();
        fl.setVisible(true);
    }//GEN-LAST:event_btnLaporanMouseClicked

    private void btnTentangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTentangMouseClicked
        FormSupir fs = new FormSupir();
        fs.setVisible(true);
    }//GEN-LAST:event_btnTentangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonClose;
    private javax.swing.JPanel ButtonMax;
    private javax.swing.JPanel ButtonMin;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HideMenu;
    private javax.swing.JPanel Icon;
    private javax.swing.JPanel LineHideMenu;
    private javax.swing.JPanel LineLogout;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel MenuHide;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JPanel btnLaporan;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JPanel btnMobil;
    private javax.swing.JPanel btnPelanggan;
    private javax.swing.JPanel btnPengembalian;
    private javax.swing.JPanel btnPinjam;
    private javax.swing.JPanel btnTentang;
    private javax.swing.JLabel buttonhidemenu;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel main_panel;
    private javax.swing.JLabel maximize;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel minimize;
    // End of variables declaration//GEN-END:variables

    Object setContentPane() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
