/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author One For All
 */
public class FormLaporan extends javax.swing.JFrame {
    private final Connection conn = new koneksi().connect();
    JasperReport jasperReport; 
    JasperDesign jasperDesign;
    JasperPrint jasperPrint;
    HashMap parameter = new HashMap();
    int mousepX ;
    int mousepY ;
    public FormLaporan() {
        initComponents();
        Locale locale = new Locale("id","ID");
        Locale.setDefault(locale);
        setLocationRelativeTo(null); 
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelMobil2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnTransaksi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tgl2 = new javax.swing.JTextField();
        tgl1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        panelMobil1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSupir = new javax.swing.JButton();
        btnPelanggan = new javax.swing.JButton();
        btnMobil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-cancel-30.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 30, -1));

        panelMobil2.setBackground(new java.awt.Color(0, 71, 67));
        panelMobil2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cetak", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelMobil2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Eras Demi ITC", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(249, 188, 97));
        jLabel7.setText("S/D");
        panelMobil2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        btnTransaksi.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-print-32.png"))); // NOI18N
        btnTransaksi.setText("Print");
        btnTransaksi.setInheritsPopupMenu(true);
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        panelMobil2.add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, 30));

        jLabel8.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(249, 188, 97));
        jLabel8.setText("(DD-MM-YYYY)");
        panelMobil2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        tgl2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tgl2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tgl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl2ActionPerformed(evt);
            }
        });
        panelMobil2.add(tgl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 110, 30));

        tgl1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tgl1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tgl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl1ActionPerformed(evt);
            }
        });
        panelMobil2.add(tgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 110, 30));

        jLabel9.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(249, 188, 97));
        jLabel9.setText("Laporan Data Transaksi");
        panelMobil2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jPanel1.add(panelMobil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 530, 220));

        panelMobil1.setBackground(new java.awt.Color(0, 71, 67));
        panelMobil1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cetak", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelMobil1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 188, 97));
        jLabel2.setText("Laporan Data Pelangggan");
        panelMobil1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(249, 188, 97));
        jLabel3.setText("Laporan Data Mobil");
        panelMobil1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(249, 188, 97));
        jLabel6.setText("Laporan Data Supir");
        panelMobil1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        btnSupir.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnSupir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-print-32.png"))); // NOI18N
        btnSupir.setText("Print");
        btnSupir.setInheritsPopupMenu(true);
        btnSupir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupirActionPerformed(evt);
            }
        });
        panelMobil1.add(btnSupir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 120, 30));

        btnPelanggan.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-print-32.png"))); // NOI18N
        btnPelanggan.setText("Print");
        btnPelanggan.setInheritsPopupMenu(true);
        btnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelangganActionPerformed(evt);
            }
        });
        panelMobil1.add(btnPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 120, 30));

        btnMobil.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnMobil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-print-32.png"))); // NOI18N
        btnMobil.setText("Print");
        btnMobil.setInheritsPopupMenu(true);
        btnMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMobilActionPerformed(evt);
            }
        });
        panelMobil1.add(btnMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 120, 30));

        jPanel1.add(panelMobil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 530, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bg menu.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 530));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 530);

        setSize(new java.awt.Dimension(630, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        mousepX = getX();
        mousepY = getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int koordinatX = evt.getXOnScreen();
        int koordinatY = evt.getYOnScreen();
        this.setLocation(koordinatX-mousepX, koordinatY-mousepY);
    }//GEN-LAST:event_jLabel1MouseDragged
    

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        try{
            File file = new File("src/report/dataTransaksi.jrxml");
            jasperDesign = JRXmlLoader.load(file);
            Map <String,Object> parham = new HashMap<>();
            parham.put("tgl1", tgl1.getText());
            parham.put("tgl2", tgl2.getText());
            jasperReport = JasperCompileManager.compileReport(jasperDesign);
            jasperPrint = JasperFillManager.fillReport(jasperReport,parham,conn);
            JasperViewer.viewReport(jasperPrint, false);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Tidak Bisa Cetak Laporan Transaksi" + e.getMessage());
        }
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnSupirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupirActionPerformed
        try{
            File file = new File("src/report/dataSupir.jrxml");
            jasperDesign = JRXmlLoader.load(file);
            Map <String,Object> parham = new HashMap<>();
             parham.clear();
            jasperReport = JasperCompileManager.compileReport(jasperDesign);
            jasperPrint = JasperFillManager.fillReport(jasperReport,parham,conn);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak dapat dicetak!"+ "\n" + e.getMessage(), "Cetak Data", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_btnSupirActionPerformed

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelangganActionPerformed
        try{
            File file = new File("src/report/dataPelanggan.jrxml");
            jasperDesign = JRXmlLoader.load(file);
            Map <String,Object> parham = new HashMap<>();
             parham.clear();
            jasperReport = JasperCompileManager.compileReport(jasperDesign);
            jasperPrint = JasperFillManager.fillReport(jasperReport,parham,conn);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak dapat dicetak!"+ "\n" + e.getMessage(), "Cetak Data", JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_btnPelangganActionPerformed

    private void btnMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMobilActionPerformed
        try{
            File file = new File("src/report/dataMobil.jrxml");
            jasperDesign = JRXmlLoader.load(file);
            Map <String,Object> parham = new HashMap<>();
             parham.clear();
            jasperReport = JasperCompileManager.compileReport(jasperDesign);
            jasperPrint = JasperFillManager.fillReport(jasperReport,parham,conn);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak dapat dicetak!"+ "\n" + e.getMessage(), "Cetak Data", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_btnMobilActionPerformed

    private void tgl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl2ActionPerformed

    private void tgl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMobil;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnSupir;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelMobil1;
    private javax.swing.JPanel panelMobil2;
    private javax.swing.JTextField tgl1;
    private javax.swing.JTextField tgl2;
    // End of variables declaration//GEN-END:variables
}
