/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import java.io.File;
import java.sql.*;
import java.util.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author One For All
 */
public class FormTransaksi extends javax.swing.JPanel {
    private final Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    PreparedStatement pStat;
    String a,b,c,d,e,f,g,h,i,j,k,l,m,n;
    String pinjam,kembali;
    public FormTransaksi() {
        initComponents();
        Locale locale = new Locale("id","ID");
        Locale.setDefault(locale);
        datatable();
        noplat();
        autoNumber();
        pelanggan();
        nonaktifDriver();
        driver();
        jCheckBox1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        tCari = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tLama = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnSave1 = new javax.swing.JButton();
        tglPinjam = new com.toedter.calendar.JDateChooser();
        tglKembali = new com.toedter.calendar.JDateChooser();
        tLama1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tTotal = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        tBayar = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        PanelDataPelanggan = new javax.swing.JPanel();
        tId = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cNama = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        NamaSupirr = new javax.swing.JLabel();
        cNoPlat = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        tNik = new javax.swing.JLabel();
        cSupir = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        IdSupirrr = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        NamaSupirrr = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tTelp = new javax.swing.JLabel();
        tEmail = new javax.swing.JLabel();
        tAlamat = new javax.swing.JLabel();
        tHarga = new javax.swing.JLabel();
        tMerk = new javax.swing.JLabel();
        tType = new javax.swing.JLabel();
        tIdSupir = new javax.swing.JLabel();
        tTransmisi = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        tTahun = new javax.swing.JLabel();
        TelpSupirr = new javax.swing.JLabel();
        TelpSupirrr = new javax.swing.JLabel();
        tTelpSupir = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        IdSupirr = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tKet = new javax.swing.JLabel();
        tJasa = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        TelpSupirrr1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1330, 800));
        setPreferredSize(new java.awt.Dimension(1330, 800));

        kGradientPanel2.setkEndColor(new java.awt.Color(98, 215, 196));
        kGradientPanel2.setkGradientFocus(2000);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 87, 64));
        kGradientPanel2.setMinimumSize(new java.awt.Dimension(100, 300));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelTransaksi.setBackground(new java.awt.Color(1, 135, 100));
        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);

        kGradientPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 1200, 240));

        tCari.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        tCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCariActionPerformed(evt);
            }
        });
        kGradientPanel2.add(tCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 160, 30));

        jPanel2.setBackground(new java.awt.Color(0, 71, 67));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Pinjam Mobil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setFont(new java.awt.Font("Eras Demi ITC", 1, 11)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/save-16x16i.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setInheritsPopupMenu(true);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 100, 30));

        btnDelete.setFont(new java.awt.Font("Eras Demi ITC", 1, 11)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trash.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setInheritsPopupMenu(true);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 100, 30));

        btnClear.setFont(new java.awt.Font("Eras Demi ITC", 1, 11)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh26.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.setInheritsPopupMenu(true);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 100, 30));

        jLabel11.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(249, 188, 97));
        jLabel11.setText("Tgl Peminjaman");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(249, 188, 97));
        jLabel12.setText("Tgl Pengembalian");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel14.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(249, 188, 97));
        jLabel14.setText("Bayar");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        tLama.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tLama.setForeground(new java.awt.Color(249, 188, 97));
        jPanel2.add(tLama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 30, 20));

        btnEdit.setFont(new java.awt.Font("Eras Demi ITC", 1, 11)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit_f2.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setInheritsPopupMenu(true);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel2.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 100, 30));

        btnSave1.setFont(new java.awt.Font("Eras Demi ITC", 1, 11)); // NOI18N
        btnSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/save-16x16i.png"))); // NOI18N
        btnSave1.setText("Hitung");
        btnSave1.setInheritsPopupMenu(true);
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 100, 30));

        tglPinjam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglPinjamPropertyChange(evt);
            }
        });
        jPanel2.add(tglPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 30, 100, -1));

        tglKembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglKembaliPropertyChange(evt);
            }
        });
        jPanel2.add(tglKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 100, -1));

        tLama1.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tLama1.setForeground(new java.awt.Color(249, 188, 97));
        tLama1.setText("Hari");
        jPanel2.add(tLama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 30, 20));

        jLabel15.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(249, 188, 97));
        jLabel15.setText("Lama Peminjaman");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel29.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(249, 188, 97));
        jLabel29.setText("Total Harga");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        tTotal.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tTotal.setForeground(new java.awt.Color(249, 188, 97));
        jPanel2.add(tTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 100, 20));

        jLabel28.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(249, 188, 97));
        jLabel28.setText(":");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 10, -1));

        jLabel35.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(249, 188, 97));
        jLabel35.setText(":");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 10, -1));

        jLabel36.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(249, 188, 97));
        jLabel36.setText(":");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 10, -1));

        jLabel38.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(249, 188, 97));
        jLabel38.setText(":");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 10, -1));

        jLabel39.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(249, 188, 97));
        jLabel39.setText(":");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 10, -1));

        tBayar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBayarActionPerformed(evt);
            }
        });
        jPanel2.add(tBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 100, -1));

        kGradientPanel2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 320, 390));

        btnSearch.setFont(new java.awt.Font("Eras Demi ITC", 1, 11)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cari.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setInheritsPopupMenu(true);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 100, 30));

        PanelDataPelanggan.setBackground(new java.awt.Color(0, 71, 67));
        PanelDataPelanggan.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Data Pelanggan & Mobil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        PanelDataPelanggan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tId.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tId.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 210, 20));

        jLabel9.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(249, 188, 97));
        jLabel9.setText("No Telpon");
        PanelDataPelanggan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 188, 97));
        jLabel2.setText("E-mail");
        PanelDataPelanggan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(249, 188, 97));
        jLabel10.setText("Alamat");
        PanelDataPelanggan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        cNama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --" }));
        cNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNamaActionPerformed(evt);
            }
        });
        PanelDataPelanggan.add(cNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 170, -1));

        jLabel6.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(249, 188, 97));
        jLabel6.setText("Type");
        PanelDataPelanggan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(249, 188, 97));
        jLabel5.setText("Plat Nomor");
        PanelDataPelanggan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 188, 97));
        jLabel1.setText("Harga");
        PanelDataPelanggan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(249, 188, 97));
        jLabel8.setText("Transmisi");
        PanelDataPelanggan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jLabel13.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(249, 188, 97));
        jLabel13.setText("Nama");
        PanelDataPelanggan.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel16.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(249, 188, 97));
        jLabel16.setText("Merk");
        PanelDataPelanggan.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        NamaSupirr.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        NamaSupirr.setForeground(new java.awt.Color(249, 188, 97));
        NamaSupirr.setText("Nama Supir");
        PanelDataPelanggan.add(NamaSupirr, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));

        cNoPlat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --" }));
        cNoPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNoPlatActionPerformed(evt);
            }
        });
        PanelDataPelanggan.add(cNoPlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 120, -1));

        jLabel19.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(249, 188, 97));
        jLabel19.setText(":");
        PanelDataPelanggan.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 10, -1));

        jCheckBox1.setFont(new java.awt.Font("Eras Demi ITC", 1, 10)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Sewa Mobil dengan Supir ?");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        PanelDataPelanggan.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        tNik.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tNik.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tNik, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 200, 20));

        cSupir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --" }));
        cSupir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSupirActionPerformed(evt);
            }
        });
        PanelDataPelanggan.add(cSupir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 120, -1));

        jLabel20.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(249, 188, 97));
        jLabel20.setText("NIK");
        PanelDataPelanggan.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel21.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(249, 188, 97));
        jLabel21.setText(":");
        PanelDataPelanggan.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 10, -1));

        jLabel22.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(249, 188, 97));
        jLabel22.setText(":");
        PanelDataPelanggan.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 10, -1));

        jLabel23.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(249, 188, 97));
        jLabel23.setText(":");
        PanelDataPelanggan.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 10, -1));

        jLabel24.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(249, 188, 97));
        jLabel24.setText(":");
        PanelDataPelanggan.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 10, -1));

        jLabel25.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(249, 188, 97));
        jLabel25.setText(":");
        PanelDataPelanggan.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 10, -1));

        jLabel26.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(249, 188, 97));
        jLabel26.setText(":");
        PanelDataPelanggan.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 10, -1));

        jLabel27.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(249, 188, 97));
        jLabel27.setText(":");
        PanelDataPelanggan.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 10, -1));

        IdSupirrr.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        IdSupirrr.setForeground(new java.awt.Color(249, 188, 97));
        IdSupirrr.setText(":");
        PanelDataPelanggan.add(IdSupirrr, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 10, -1));

        jLabel30.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(249, 188, 97));
        jLabel30.setText(":");
        PanelDataPelanggan.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 10, -1));

        NamaSupirrr.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        NamaSupirrr.setForeground(new java.awt.Color(249, 188, 97));
        NamaSupirrr.setText(":");
        PanelDataPelanggan.add(NamaSupirrr, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 10, -1));

        jLabel32.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(249, 188, 97));
        jLabel32.setText("Id Transaksi");
        PanelDataPelanggan.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        tTelp.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tTelp.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 200, 20));

        tEmail.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tEmail.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 200, 20));

        tAlamat.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tAlamat.setForeground(new java.awt.Color(249, 188, 97));
        tAlamat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelDataPelanggan.add(tAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 200, 20));

        tHarga.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tHarga.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 130, 20));

        tMerk.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tMerk.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tMerk, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 130, 20));

        tType.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tType.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tType, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 130, 20));

        tIdSupir.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tIdSupir.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tIdSupir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 130, 20));

        tTransmisi.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tTransmisi.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tTransmisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 130, 20));

        jLabel33.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(249, 188, 97));
        jLabel33.setText("Tahun");
        PanelDataPelanggan.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jLabel34.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(249, 188, 97));
        jLabel34.setText(":");
        PanelDataPelanggan.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 10, -1));

        tTahun.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tTahun.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 130, 20));

        TelpSupirr.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        TelpSupirr.setForeground(new java.awt.Color(249, 188, 97));
        TelpSupirr.setText("No Telp");
        PanelDataPelanggan.add(TelpSupirr, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        TelpSupirrr.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        TelpSupirrr.setForeground(new java.awt.Color(249, 188, 97));
        TelpSupirrr.setText(":");
        PanelDataPelanggan.add(TelpSupirrr, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 10, -1));

        tTelpSupir.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tTelpSupir.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tTelpSupir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 130, 20));

        jLabel37.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(249, 188, 97));
        jLabel37.setText(":");
        PanelDataPelanggan.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 10, -1));

        IdSupirr.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        IdSupirr.setForeground(new java.awt.Color(249, 188, 97));
        IdSupirr.setText("Id Supir");
        PanelDataPelanggan.add(IdSupirr, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        jLabel31.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(249, 188, 97));
        jLabel31.setText(":");
        PanelDataPelanggan.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 10, -1));

        tKet.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tKet.setForeground(new java.awt.Color(249, 188, 97));
        tKet.setText("Jasa Supir");
        PanelDataPelanggan.add(tKet, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 80, 20));

        tJasa.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tJasa.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 130, 20));

        btnPrint.setFont(new java.awt.Font("Eras Demi ITC", 1, 11)); // NOI18N
        btnPrint.setIcon(new javax.swing.ImageIcon("C:\\Users\\bamba\\Downloads\\icons8-print-36.png")); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setInheritsPopupMenu(true);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        PanelDataPelanggan.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 110, 30));

        TelpSupirrr1.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        TelpSupirrr1.setForeground(new java.awt.Color(249, 188, 97));
        TelpSupirrr1.setText(":");
        PanelDataPelanggan.add(TelpSupirrr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 10, -1));

        kGradientPanel2.add(PanelDataPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 850, 300));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/key car.png"))); // NOI18N
        kGradientPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 480, 380));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bgkayu.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        kGradientPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1330, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

     protected void kosong(){
        tMerk.setText("");
        tType.setText("");
        tIdSupir.setText("");
        tJasa.setText("");
        tTahun.setText("");
        tTelpSupir.setText("");
        tTransmisi.setText("");
        tHarga.setText("");
        tNik.setText("");
        tAlamat.setText("");
        tTelp.setText("");
        tEmail.setText("");
        tLama.setText("");
        tTotal.setText("");
        cNoPlat.setSelectedIndex(0);
        cNama.setSelectedIndex(0);
        jCheckBox1.setSelected(false);
        tglPinjam.setDate(null);
        tglKembali.setDate(null);
        autoNumber();
        jCheckBox1.setEnabled(false);
        nonaktifDriver();
    }
    
    protected void datatable(){
        Object[] Baris={"Id Transaksi", "NIK", "Nama Pelanggan", "Merk", "Type", "Plat Nomor", "Tanggal Pinjam", "Tanggal Kembali", "Harga", "Lama Sewa", "Total Harga", "Supir", "Jasa Supir", "Bayar"};
        tabmode = new DefaultTableModel(null,Baris);
        tabelTransaksi.setModel(tabmode);
        String sql="SELECT * from pinjam INNER JOIN pelanggan ON pelanggan.nik = pinjam.nik INNER JOIN mobil ON mobil.no_plat=pinjam.no_plat WHERE status_transaksi='Berjalan' AND (id_transaksi LIKE '%"+tCari.getText()+"%'"
                + "OR pinjam.nik LIKE '%"+tCari.getText()+"%' "
                + "OR nama LIKE '%"+tCari.getText()+"%' "
                + "OR pinjam.no_plat LIKE '%"+tCari.getText()+"%' "
                + "OR type LIKE '%"+tCari.getText()+"%' "
                + "OR harga LIKE '%"+tCari.getText()+"%' "
                + "OR tgl_pinjam LIKE '%"+tCari.getText()+"%' "
                + "OR tgl_kembali LIKE '%"+tCari.getText()+"%' "
                + "OR lama_pinjam LIKE '%"+tCari.getText()+"%' "
                + "OR total LIKE '%"+tCari.getText()+"%' "
                + "OR id_supir LIKE '%"+tCari.getText()+"%' "
                + "OR bayar LIKE '%"+tCari.getText()+"%' )";
        try{
            java.sql.Statement stat=conn.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                a=hasil.getString("id_transaksi");
                b=hasil.getString("nik");
                c=hasil.getString("nama");
                d=hasil.getString("merk");
                e=hasil.getString("type");
                f=hasil.getString("no_plat");
                g=hasil.getString("tgl_pinjam");
                h=hasil.getString("tgl_kembali");
                i=hasil.getString("harga");
                j=hasil.getString("lama_pinjam");
                k=hasil.getString("total");
                l=hasil.getString("id_supir");
                if(l.equals("Tanpa Supir")){
                    m="-";
                    System.out.println(m);
                }else{
                    String sql2="SELECT * FROM supir WHERE id_supir ='"+l+"'";
                    java.sql.Statement stat2 = conn.createStatement();
                    ResultSet hasil2 = stat2.executeQuery(sql2);
                    while(hasil2.next()){
                        l=hasil2.getString("nama_supir");
                        m=hasil2.getString("biaya");
                        System.out.println(l);
                }
                n=hasil.getString("bayar");
            }
                String[] data={a,b,c,d,e,f,g,h,i,j,k,l,m,n};
                tabmode.addRow(data);
            }
            autoNumber();
        }catch(Exception e){
            
        }
    }
    
    protected void dataMobil(){
        String sql = "SELECT * FROM mobil WHERE no_plat='"+cNoPlat.getSelectedItem().toString()+"'";
        try{
            java.sql.Statement stat=conn.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                a = hasil.getString("merk");
                b = hasil.getString("type");
                c = hasil.getString("tahun");
                d = hasil.getString("transmisi");
                e = hasil.getString("harga");
                tMerk.setText(a);
                tType.setText(b);
                tTahun.setText(c);
                tTransmisi.setText(d);
                tHarga.setText(e);
                jCheckBox1.setEnabled(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Tidak Bisa Menampilkan Tabel" + e);
        }
    }
    

    
    protected void noplat(){
        String sql = "SELECT * FROM mobil WHERE status='Tersedia'";
        try{
            java.sql.Statement stat=conn.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                cNoPlat.addItem(hasil.getString("no_plat"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No Plat Tidak Tampil" + e);
        }
    }
    
    
    protected void pelanggan(){
        String sql = "SELECT * FROM pelanggan";
        try{
            java.sql.Statement stat=conn.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                cNama.addItem(hasil.getString("nama"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Pelanggan Tidak Tampil" + e);
        }
    }
    
    private void hitung(){
        try {
            DateFormat format = new SimpleDateFormat("dd-MM-yyyy");
            System.out.println(pinjam);
            System.out.println(kembali);
            Date tanggalPinjam = (Date) format.parse(pinjam);
            Date tanggalKembali = (Date) format.parse(kembali);
            System.out.println(tanggalPinjam);
            System.out.println(tanggalKembali);
            long tanggalPinjam1 = tanggalPinjam.getTime();
            long tanggalKembali1 = tanggalKembali.getTime();
            System.out.println(tanggalPinjam1);
            System.out.println(tanggalKembali1);
            long diff = tanggalKembali1 - tanggalPinjam1;
            long lama = diff / (24*60*60*1000);
            System.out.println(diff);
            System.out.println(lama);
            int hari = (int)lama + 1;
                if(supir==true){
                    jCheckBox1.setSelected(supir);
                    int jasa = Integer.parseInt(tJasa.getText());
                    int harga = Integer.parseInt(tHarga.getText());
                    int total = hari * (harga+jasa);
                    tTotal.setText(String.valueOf(total));
                }else{
                     int harga = Integer.parseInt(tHarga.getText());
                    int total = hari * harga;
                    tTotal.setText(String.valueOf(total));
                 }
            tLama.setText(String.valueOf(hari));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hitung Gagal " + e);
        }
    }
    
    private void autoNumber(){
        String n = "T00000";
        int i = 0;
        try{
            Statement st = conn.createStatement();
            String sql = "SELECT id_transaksi FROM pinjam ORDER BY id_transaksi DESC LIMIT 1";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                n = rs.getString("id_transaksi");
            }
            n = n.substring(1);
            System.out.println(n);
            i = Integer.parseInt(n)+1;
            n = "0000" + i;
            n = "T"+ n.substring(n.length()-5);
            tId.setText(n);
        }catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    private void tambahTransaksi(){
        String sql = "INSERT INTO pinjam (id_transaksi,nik,no_plat,tgl_pinjam,tgl_kembali,lama_pinjam,total,bayar,id_supir) VALUES(?,?,?,?,?,?,?,?,?)";
        try {
            pStat = conn.prepareStatement(sql);
            pStat.setString(1,tId.getText());
            pStat.setString(2,tNik.getText());
            pStat.setString(3,cNoPlat.getSelectedItem().toString());
            try {
                String tampilan = "dd-MM-YYYY";
                SimpleDateFormat fm = new SimpleDateFormat(tampilan);
                String tanggalPnjm = String.valueOf(fm.format(tglPinjam.getDate()));
                String tanggalKmbli = String.valueOf(fm.format(tglKembali.getDate()));
                pStat.setString(4,tanggalPnjm);
                pStat.setString(5,tanggalKmbli);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Masukkan Tanggal !");
            }
            pStat.setString(6,tLama.getText());
            pStat.setString(7,tTotal.getText());
            String bayar = tBayar.getText();
            if(bayar.equals("")){
                bayar = "0";
            }
            pStat.setString(8,bayar);
            if(supir==true){
                pStat.setString(9,tIdSupir.getText());
            }else{
                pStat.setString(9,"Tanpa Supir");
                System.out.println("Tanpa Supir");
            }
            pStat.executeUpdate();
            String sql2 = "UPDATE mobil SET status='Tidak Tersedia' WHERE no_plat='"+cNoPlat.getSelectedItem().toString()+"'";
            PreparedStatement pStat2 = conn.prepareStatement(sql2);
            pStat2.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            cNoPlat.removeItem(cNoPlat.getSelectedItem());
            kosong();
            datatable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e);
        }
    }
    
    private void hapus(){
        int ok = JOptionPane.showConfirmDialog(null, "Hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok==0){
            String sql = "DELETE FROM pinjam WHERE id_transaksi='"+tId.getText()+"'";
            try {
                pStat = conn.prepareStatement(sql);
                pStat.executeUpdate();
                String sql2 = "UPDATE mobil SET status='Tersedia' WHERE no_plat='"+cNoPlat.getSelectedItem().toString()+"'";
                PreparedStatement pStat2 = conn.prepareStatement(sql2);
                pStat2.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                kosong();
                cNama.requestFocus();
                datatable();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal dihapus");
            }
        }
    }
    
    private void ubah(){
        String tampilan ="dd-MM-YYYY";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggalPnjm=String.valueOf(fm.format(tglPinjam.getDate()));
        String tanggalKmbli=String.valueOf(fm.format(tglKembali.getDate()));
        String sql = "UPDATE pinjam SET nik=?, no_plat=?, tgl_pinjam=?, tgl_kembali=?, lama_pinjam=?, total=?, bayar=?, id_supir=? WHERE id_transaksi='"+tId.getText()+"'";
        try {
            pStat = conn.prepareStatement(sql);
            pStat.setString(1, tNik.getText());
            pStat.setString(2, cNoPlat.getSelectedItem().toString());
            pStat.setString(3, tanggalPnjm);
            pStat.setString(4, tanggalKmbli);
            pStat.setString(5, tLama.getText());
            pStat.setString(6, tTotal.getText());
            String bayar=tBayar.getText();
            if(bayar.equals("")){
                bayar = "0";
                pStat.setString(7, bayar);
            }
            pStat.setString(7, bayar);
            if(supir==true){
                pStat.setString(8,tIdSupir.getText());
            }else{
                pStat.setString(8,"Tanpa Supir");
                System.out.println("Tanpa Supir");
            }
            pStat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            kosong();
            cNama.requestFocus();
            datatable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal diubah" +e);
        }
    }
    boolean supir;
    private void nonaktifDriver(){
        supir=false;
        jCheckBox1.setSelected(supir);
        cSupir.setVisible(supir);
        IdSupirr.setVisible(supir);
        IdSupirrr.setVisible(supir);
        NamaSupirr.setVisible(supir);
        NamaSupirrr.setVisible(supir);
        TelpSupirr.setVisible(supir);
        TelpSupirrr.setVisible(supir);
        TelpSupirrr1.setVisible(supir);
        tKet.setVisible(supir);
        tJasa.setVisible(supir);
    }
    private void driver(){
        String sql = "SELECT * FROM supir";
        try{
            java.sql.Statement stat=conn.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                cSupir.addItem(hasil.getString("nama_supir"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Driver Tidak Tampil "+e);
        }
    }
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        datatable();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        hitung();
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        ubah();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        kosong();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        hapus();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        tambahTransaksi();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCariActionPerformed

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
        int bar = tabelTransaksi.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        tId.setText(a);
        String b = tabmode.getValueAt(bar, 1).toString();
        tNik.setText(b);
        String sql = "SELECT * FROM pinjam INNER JOIN pelanggan ON pelanggan.nik=pinjam.nik INNER JOIN mobil ON mobil.no_plat=pinjam.no_plat WHERE id_transaksi='"+a+"'";
        try {
            java.sql.Statement cStat= conn.createStatement();
            ResultSet hasil = cStat.executeQuery(sql);
            while(hasil.next()){
                String c = hasil.getString("nama");
                String d = hasil.getString("alamat");
                String e = hasil.getString("telp");
                String f = hasil.getString("email");
                String g = hasil.getString("no_plat");
                String h = hasil.getString("merk");
                String i = hasil.getString("type");
                String j = hasil.getString("tahun");
                String l = hasil.getString("transmisi");
                String m = hasil.getString("harga");
                System.out.println(g);
                cNama.setSelectedItem(c);
                tAlamat.setText(d);
                tTelp.setText(e);
                tEmail.setText(f);
                tMerk.setText(h);
                tType.setText(i);
                tTahun.setText(j);
                tTransmisi.setText(l);
                tHarga.setText(m);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        try{
        java.util.Date n = new SimpleDateFormat("dd-MM-YYYY").parse((String)tabmode.getValueAt(bar, 6));
        tglPinjam.setDate(n);
        java.util.Date o = new SimpleDateFormat("dd-MM-YYYY").parse((String)tabmode.getValueAt(bar, 7));
        tglKembali.setDate(o);
        } catch (ParseException ex) {
        java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        String r = tabmode.getValueAt(bar,5).toString();
        cNoPlat.setSelectedItem(r);
        String plat = cNoPlat.getSelectedItem().toString();
        if(plat.equals(r)){
        }else{
            cNoPlat.addItem(r);
            cNoPlat.setSelectedItem(r);
        }
        String p = tabmode.getValueAt(bar, 9).toString();
        String q = tabmode.getValueAt(bar, 10).toString();
        String s = tabmode.getValueAt(bar, 11).toString();
        String t = tabmode.getValueAt(bar, 12).toString();
        tLama.setText(p);
        tTotal.setText(q);
        if(s.equals("Tanpa Supir")){
                jCheckBox1.setSelected(supir);
                cSupir.setSelectedIndex(0);
                tIdSupir.setText("");
                tTelpSupir.setText("");
                tJasa.setText("");
                cSupir.setVisible(false);
                tIdSupir.setVisible(false);
                tTelpSupir.setVisible(false);
                TelpSupirr.setVisible(false);
                TelpSupirrr.setVisible(false);
                TelpSupirrr1.setVisible(false);
                tKet.setVisible(false);
                tJasa.setVisible(false);
                IdSupirr.setVisible(false);
                IdSupirrr.setVisible(false);
                NamaSupirr.setVisible(false);
                NamaSupirrr.setVisible(false);
        }else{
                jCheckBox1.setSelected(supir);
                cSupir.setVisible(true);
                tIdSupir.setVisible(true);
                tTelpSupir.setVisible(true);
                TelpSupirr.setVisible(true);
                TelpSupirrr.setVisible(true);
                TelpSupirrr1.setVisible(true);
                tKet.setVisible(true);
                tJasa.setVisible(true);
                IdSupirr.setVisible(true);
                IdSupirrr.setVisible(true);
                NamaSupirr.setVisible(true);
                NamaSupirrr.setVisible(true);
                String sql2="SELECT id_supir FROM pinjam WHERE id_transaksi='"+a+"'";
                java.sql.Statement stat2;
            try {
                stat2 = conn.createStatement();
                ResultSet hasil2 = stat2.executeQuery(sql2);
                while(hasil2.next()){
                    s=hasil2.getString("id_supir");
                    String sql3="SELECT * FROM supir WHERE id_supir='"+s+"'";
                    java.sql.Statement stat3=conn.createStatement();
                    ResultSet hasil3 = stat3.executeQuery(sql3);
                    while(hasil3.next()){
                        String u = hasil3.getString("nama_supir");
                    t = hasil3.getString("biaya");
                    String v = hasil3.getString("telp");
                    tIdSupir.setText(s);
                    cSupir.setSelectedItem(u);
                    tTelpSupir.setText(v);
                    tJasa.setText(t);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(FormTransaksi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        String x = tabmode.getValueAt(bar, 13).toString();
    }//GEN-LAST:event_tabelTransaksiMouseClicked

    private void tglPinjamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglPinjamPropertyChange
        if (tglPinjam.getDate()!=null){
            SimpleDateFormat Format=new SimpleDateFormat("dd-MM-yyyy");
            pinjam=Format.format(tglPinjam.getDate());
        }
    }//GEN-LAST:event_tglPinjamPropertyChange

    private void tglKembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglKembaliPropertyChange
        if(tglKembali.getDate()!=null){
           SimpleDateFormat Format=new SimpleDateFormat("dd-MM-yyyy");
           kembali = Format.format(tglKembali.getDate());
        }
    }//GEN-LAST:event_tglKembaliPropertyChange

    private void cNoPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNoPlatActionPerformed
        dataMobil();
    }//GEN-LAST:event_cNoPlatActionPerformed

    private void cNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNamaActionPerformed
        String sql = "SELECT * FROM pelanggan WHERE nama='"+cNama.getSelectedItem().toString()+"';";
        try{
            java.sql.Statement stat=conn.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                a=hasil.getString("nik");
                b=hasil.getString("nama");
                c=hasil.getString("alamat");
                d=hasil.getString("telp");
                e=hasil.getString("email");
                tNik.setText(a);
                tAlamat.setText(c);
                tTelp.setText(d);
                tEmail.setText(e);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cNamaActionPerformed
    protected void pilihSupir(){
        if(supir==false){
            supir=true;
            cSupir.setVisible(supir);
            tIdSupir.setVisible(supir);
            tTelpSupir.setVisible(supir);
            TelpSupirr.setVisible(supir);
            TelpSupirrr.setVisible(supir);
            TelpSupirrr1.setVisible(supir);
            IdSupirr.setVisible(supir);
            IdSupirrr.setVisible(supir);
            NamaSupirr.setVisible(supir);
            NamaSupirrr.setVisible(supir);
            tKet.setVisible(supir);
            tJasa.setVisible(supir);
        }else{
            supir=false;
            cSupir.setSelectedIndex(0);
            tIdSupir.setText("");
            tTelpSupir.setText("");
            tJasa.setText("");
            TelpSupirr.setVisible(supir);
            TelpSupirrr.setVisible(supir);
            TelpSupirrr1.setVisible(supir);
            cSupir.setVisible(supir);
            IdSupirr.setVisible(supir);
            IdSupirrr.setVisible(supir);
            NamaSupirr.setVisible(supir);
            NamaSupirrr.setVisible(supir);
            tKet.setVisible(supir);
            tJasa.setVisible(supir);
        }
    }
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        pilihSupir();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void cSupirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSupirActionPerformed
        String sql = "SELECT * FROM supir WHERE nama_supir='"+cSupir.getSelectedItem().toString()+"';";
        try{
            java.sql.Statement stat=conn.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                a=hasil.getString("id_supir");
                b=hasil.getString("telp");
                c=hasil.getString("biaya");
                tIdSupir.setText(a);
                tTelpSupir.setText(b);
                tJasa.setText(c);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cSupirActionPerformed

    private void tBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBayarActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try{        
            File file = new File("src/report/buktiPenyewaan.jrxml");
            JasperDesign jasperDesign = JRXmlLoader.load(file);
            Map <String,Object> parham = new HashMap<>();
            parham.put("IdTransaksi", tId.getText());
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parham,conn);
            JasperViewer.viewReport(jasperPrint, false);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Tidak Bisa Cetak Struk Gaji" + e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

   
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdSupirr;
    private javax.swing.JLabel IdSupirrr;
    private javax.swing.JLabel NamaSupirr;
    private javax.swing.JLabel NamaSupirrr;
    private javax.swing.JPanel PanelDataPelanggan;
    private javax.swing.JLabel TelpSupirr;
    private javax.swing.JLabel TelpSupirrr;
    private javax.swing.JLabel TelpSupirrr1;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cNama;
    private javax.swing.JComboBox<String> cNoPlat;
    private javax.swing.JComboBox<String> cSupir;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel tAlamat;
    private javax.swing.JTextField tBayar;
    private javax.swing.JTextField tCari;
    private javax.swing.JLabel tEmail;
    private javax.swing.JLabel tHarga;
    private javax.swing.JLabel tId;
    private javax.swing.JLabel tIdSupir;
    private javax.swing.JLabel tJasa;
    private javax.swing.JLabel tKet;
    private javax.swing.JLabel tLama;
    private javax.swing.JLabel tLama1;
    private javax.swing.JLabel tMerk;
    private javax.swing.JLabel tNik;
    private javax.swing.JLabel tTahun;
    private javax.swing.JLabel tTelp;
    private javax.swing.JLabel tTelpSupir;
    private javax.swing.JLabel tTotal;
    private javax.swing.JLabel tTransmisi;
    private javax.swing.JLabel tType;
    private javax.swing.JTable tabelTransaksi;
    private com.toedter.calendar.JDateChooser tglKembali;
    private com.toedter.calendar.JDateChooser tglPinjam;
    // End of variables declaration//GEN-END:variables

    private void setExtendedState(float CENTER_ALIGNMENT) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
