/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author One For All
 */
public class FormMobil extends javax.swing.JPanel {
    private final Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form FormMobil
     */
    public FormMobil() {
        initComponents();
        datatable();
        pilihdefault();
    }
    protected void pilihdefault(){
        cHarga.setSelectedIndex(0);
        cTahun.setSelectedIndex(0);
        cPenumpang.setSelectedIndex(0);
        cMesin.setSelectedIndex(0);
        cBbm.setSelectedIndex(0);
        cKecepatan.setSelectedIndex(0);
    }
    protected void aktif(){
        tNoPlat.setEnabled(true);
        tMerk.setEnabled(true);
        tType.setEnabled(true);
        tTahun.setEnabled(true);
        tHarga.setEnabled(true);
        tBbm.setEnabled(true);
        tPenumpang.setEnabled(true);
        tMesin.setEnabled(true);
        tKecepatan.setEnabled(true);
        rt1.setEnabled(true);
        rt2.setEnabled(true);
        cStatus.setEnabled(true);
    }
    protected void kosong(){
        tNoPlat.setText("");
        tMerk.setText("");
        tType.setText("");
        tTahun.setText("");
        tBbm.setText("");
        tPenumpang.setText("");
        tMesin.setText("");
        tKecepatan.setText("");
        bgrupTransmisi.clearSelection();
        tHarga.setText("");
        cStatus.setSelectedIndex(0);
    }
    int x;
    protected void datatable(){
        Object[] Baris={"No","Plat Nomor", "Merk", "Type", "Transmisi", "Status", "Tahun", "Harga", "Jumlah Penumpang", "Kekuatan Mesin", "Konsumsi Bbm", "Kecepatan Maksimum"};
        tabmode = new DefaultTableModel(null,Baris);
        tabelMobil.setModel(tabmode);
        String sql="SELECT * from mobil WHERE no_plat LIKE '%"+tCari.getText()+"%'"
                + "OR type LIKE '%"+tCari.getText()+"%'"
                + "OR merk LIKE '%"+tCari.getText()+"%'"
                + "OR transmisi LIKE '%"+tCari.getText()+"%'"
                + "OR status LIKE '%"+tCari.getText()+"%'"
                + "OR tahun LIKE '%"+tCari.getText()+"%'"
                + "OR harga LIKE '%"+tCari.getText()+"%'"
                + "OR jumlah_penumpang LIKE '%"+tCari.getText()+"%'"
                + "OR kekuatan_mesin LIKE '%"+tCari.getText()+"%'"
                + "OR konsumsi_bbm LIKE '%"+tCari.getText()+"%'"
                + "OR kecepatan_maksimum LIKE '%"+tCari.getText()+"%'";
        try{
            java.sql.Statement stat=conn.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            x=1;
            while(hasil.next()){  
                String a=hasil.getString("no_plat");
                String b=hasil.getString("merk");
                String c=hasil.getString("type");
                String d=hasil.getString("transmisi");
                String e=hasil.getString("status");
                String f=hasil.getString("tahun");
                String g=hasil.getString("harga");
                String h=hasil.getString("jumlah_penumpang");
                String i=hasil.getString("kekuatan_mesin");
                String j=hasil.getString("konsumsi_bbm");
                String k=hasil.getString("kecepatan_maksimum");
                String no=String.valueOf(x);
                String[] data={no,a,b,c,d,e,f,g,h,i,j,k};
                tabmode.addRow(data);
                x=x+1;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Tidak Bisa Menampilkan Tabel "+e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrupBbm = new javax.swing.ButtonGroup();
        bgrupTransmisi = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMobil = new javax.swing.JTable();
        panelMobil2 = new javax.swing.JPanel();
        tCari = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        panelMobil = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tHarga = new javax.swing.JTextField();
        tTahun = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tType = new javax.swing.JTextField();
        tMerk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tNoPlat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rt1 = new javax.swing.JRadioButton();
        rt2 = new javax.swing.JRadioButton();
        cStatus = new javax.swing.JComboBox<>();
        tPenumpang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tBbm = new javax.swing.JTextField();
        tMesin = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tKecepatan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        panelMobil1 = new javax.swing.JPanel();
        tKecepatan1 = new javax.swing.JLabel();
        tTahun2 = new javax.swing.JLabel();
        tTahun1 = new javax.swing.JLabel();
        tHarga1 = new javax.swing.JLabel();
        tPenumpang1 = new javax.swing.JLabel();
        tMesin1 = new javax.swing.JLabel();
        tBbm1 = new javax.swing.JLabel();
        tTahun3 = new javax.swing.JLabel();
        tTahun4 = new javax.swing.JLabel();
        tTahun5 = new javax.swing.JLabel();
        tTahun6 = new javax.swing.JLabel();
        tTahun7 = new javax.swing.JLabel();
        tTahun8 = new javax.swing.JLabel();
        tTahun9 = new javax.swing.JLabel();
        tTahun10 = new javax.swing.JLabel();
        tTahun11 = new javax.swing.JLabel();
        tTahun12 = new javax.swing.JLabel();
        tTahun13 = new javax.swing.JLabel();
        btnSearch2 = new javax.swing.JButton();
        panelMobil3 = new javax.swing.JPanel();
        cTahun = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        cHarga = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cPenumpang = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        cMesin = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        cBbm = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        cKecepatan = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1200, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(158, 105, 35));
        kGradientPanel1.setkGradientFocus(2000);
        kGradientPanel1.setkStartColor(new java.awt.Color(224, 146, 43));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelMobil.setBackground(new java.awt.Color(1, 135, 100));
        tabelMobil.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tabelMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMobilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMobil);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 1230, 300));

        panelMobil2.setBackground(new java.awt.Color(0, 71, 67));
        panelMobil2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cari Mobil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelMobil2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tCari.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        tCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCariActionPerformed(evt);
            }
        });
        panelMobil2.add(tCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 190, 30));

        btnSearch.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cari.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setInheritsPopupMenu(true);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        panelMobil2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 110, 30));

        kGradientPanel1.add(panelMobil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 370, 80));

        panelMobil.setBackground(new java.awt.Color(0, 71, 67));
        panelMobil.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Data Mobil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelMobil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClear.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh26.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.setInheritsPopupMenu(true);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        panelMobil.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 100, 30));

        btnSave.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/save-16x16i.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setInheritsPopupMenu(true);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panelMobil.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 100, 30));

        btnDelete.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trash.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setInheritsPopupMenu(true);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        panelMobil.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 100, 30));

        btnEdit.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit_f2.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setInheritsPopupMenu(true);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        panelMobil.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 100, 30));

        jLabel8.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(249, 188, 97));
        jLabel8.setText("Status");
        panelMobil.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 188, 97));
        jLabel1.setText("Jumlah Penumpang");
        panelMobil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        tHarga.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        tHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHargaActionPerformed(evt);
            }
        });
        panelMobil.add(tHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 150, -1));

        tTahun.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        tTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTahunActionPerformed(evt);
            }
        });
        panelMobil.add(tTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 90, -1));

        jLabel7.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(249, 188, 97));
        jLabel7.setText("Tahun");
        panelMobil.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(249, 188, 97));
        jLabel3.setText("Type");
        panelMobil.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        tType.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        tType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTypeActionPerformed(evt);
            }
        });
        panelMobil.add(tType, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 150, -1));

        tMerk.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        tMerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMerkActionPerformed(evt);
            }
        });
        panelMobil.add(tMerk, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 150, -1));

        jLabel6.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(249, 188, 97));
        jLabel6.setText("Merk");
        panelMobil.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(249, 188, 97));
        jLabel5.setText(":");
        panelMobil.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 10, 20));

        tNoPlat.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        tNoPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNoPlatActionPerformed(evt);
            }
        });
        panelMobil.add(tNoPlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 120, -1));

        jLabel9.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(249, 188, 97));
        jLabel9.setText("Konsumsi Bbm");
        panelMobil.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(249, 188, 97));
        jLabel10.setText("Transmisi");
        panelMobil.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        rt1.setBackground(new java.awt.Color(0, 71, 67));
        bgrupTransmisi.add(rt1);
        rt1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        rt1.setForeground(new java.awt.Color(255, 255, 255));
        rt1.setText("Automatic");
        panelMobil.add(rt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        rt2.setBackground(new java.awt.Color(0, 71, 67));
        bgrupTransmisi.add(rt2);
        rt2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        rt2.setForeground(new java.awt.Color(255, 255, 255));
        rt2.setText("Manual");
        panelMobil.add(rt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        cStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Tidak Tersedia", " " }));
        panelMobil.add(cStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 90, -1));

        tPenumpang.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        tPenumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPenumpangActionPerformed(evt);
            }
        });
        panelMobil.add(tPenumpang, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 150, -1));

        jLabel12.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(249, 188, 97));
        jLabel12.setText("Harga");
        panelMobil.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(249, 188, 97));
        jLabel13.setText("Kekuatan Mesin");
        panelMobil.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        tBbm.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        tBbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBbmActionPerformed(evt);
            }
        });
        panelMobil.add(tBbm, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 150, -1));

        tMesin.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        tMesin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMesinActionPerformed(evt);
            }
        });
        panelMobil.add(tMesin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 150, -1));

        jLabel14.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(249, 188, 97));
        jLabel14.setText("Kecepatan Maksimum");
        panelMobil.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        tKecepatan.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        tKecepatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKecepatanActionPerformed(evt);
            }
        });
        panelMobil.add(tKecepatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 150, -1));

        jLabel15.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(249, 188, 97));
        jLabel15.setText("Plat Nomor");
        panelMobil.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 20));

        jLabel16.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(249, 188, 97));
        jLabel16.setText(":");
        panelMobil.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 10, 20));

        jLabel17.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(249, 188, 97));
        jLabel17.setText(":");
        panelMobil.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 10, 20));

        jLabel18.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(249, 188, 97));
        jLabel18.setText(":");
        panelMobil.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 10, 20));

        jLabel19.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(249, 188, 97));
        jLabel19.setText(":");
        panelMobil.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 10, 20));

        jLabel20.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(249, 188, 97));
        jLabel20.setText(":");
        panelMobil.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 10, 20));

        jLabel21.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(249, 188, 97));
        jLabel21.setText(":");
        panelMobil.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 10, 20));

        jLabel22.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(249, 188, 97));
        jLabel22.setText(":");
        panelMobil.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 10, 20));

        jLabel23.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(249, 188, 97));
        jLabel23.setText(":");
        panelMobil.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 10, 20));

        jLabel24.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(249, 188, 97));
        jLabel24.setText(":");
        panelMobil.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 10, 20));

        jLabel25.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(249, 188, 97));
        jLabel25.setText(":");
        panelMobil.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 10, 20));

        kGradientPanel1.add(panelMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 840, 290));

        panelMobil1.setBackground(new java.awt.Color(0, 71, 67));
        panelMobil1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Kriteria Mobil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelMobil1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tKecepatan1.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tKecepatan1.setForeground(new java.awt.Color(249, 188, 97));
        tKecepatan1.setText(" ");
        panelMobil1.add(tKecepatan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 270, -1));

        tTahun2.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tTahun2.setForeground(new java.awt.Color(249, 188, 97));
        tTahun2.setText("Kecepatan");
        panelMobil1.add(tTahun2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 70, -1));

        tTahun1.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tTahun1.setForeground(new java.awt.Color(249, 188, 97));
        tTahun1.setText(" ");
        panelMobil1.add(tTahun1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 270, -1));

        tHarga1.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tHarga1.setForeground(new java.awt.Color(249, 188, 97));
        tHarga1.setText(" ");
        panelMobil1.add(tHarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 270, -1));

        tPenumpang1.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tPenumpang1.setForeground(new java.awt.Color(249, 188, 97));
        tPenumpang1.setText(" ");
        panelMobil1.add(tPenumpang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 270, -1));

        tMesin1.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tMesin1.setForeground(new java.awt.Color(249, 188, 97));
        tMesin1.setText(" ");
        panelMobil1.add(tMesin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 270, -1));

        tBbm1.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tBbm1.setForeground(new java.awt.Color(249, 188, 97));
        tBbm1.setText(" ");
        panelMobil1.add(tBbm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 270, -1));

        tTahun3.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tTahun3.setForeground(new java.awt.Color(249, 188, 97));
        tTahun3.setText("Bbm");
        panelMobil1.add(tTahun3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 50, -1));

        tTahun4.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tTahun4.setForeground(new java.awt.Color(249, 188, 97));
        tTahun4.setText("Mesin");
        panelMobil1.add(tTahun4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, -1));

        tTahun5.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tTahun5.setForeground(new java.awt.Color(249, 188, 97));
        tTahun5.setText("Penumpang");
        panelMobil1.add(tTahun5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        tTahun6.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tTahun6.setForeground(new java.awt.Color(249, 188, 97));
        tTahun6.setText("Harga");
        panelMobil1.add(tTahun6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, -1));

        tTahun7.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tTahun7.setForeground(new java.awt.Color(249, 188, 97));
        tTahun7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tTahun7.setText(":");
        panelMobil1.add(tTahun7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 10, -1));

        tTahun8.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tTahun8.setForeground(new java.awt.Color(249, 188, 97));
        tTahun8.setText("Tahun");
        panelMobil1.add(tTahun8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, -1));

        tTahun9.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tTahun9.setForeground(new java.awt.Color(249, 188, 97));
        tTahun9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tTahun9.setText(":");
        panelMobil1.add(tTahun9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 10, -1));

        tTahun10.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tTahun10.setForeground(new java.awt.Color(249, 188, 97));
        tTahun10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tTahun10.setText(":");
        panelMobil1.add(tTahun10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 10, -1));

        tTahun11.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tTahun11.setForeground(new java.awt.Color(249, 188, 97));
        tTahun11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tTahun11.setText(":");
        panelMobil1.add(tTahun11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 10, -1));

        tTahun12.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tTahun12.setForeground(new java.awt.Color(249, 188, 97));
        tTahun12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tTahun12.setText(":");
        panelMobil1.add(tTahun12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 10, -1));

        tTahun13.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        tTahun13.setForeground(new java.awt.Color(249, 188, 97));
        tTahun13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tTahun13.setText(":");
        panelMobil1.add(tTahun13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 10, -1));

        btnSearch2.setFont(new java.awt.Font("Eras Demi ITC", 1, 12)); // NOI18N
        btnSearch2.setIcon(new javax.swing.ImageIcon("C:\\Users\\bamba\\Downloads\\icons8-more-16.png")); // NOI18N
        btnSearch2.setText("More");
        btnSearch2.setInheritsPopupMenu(true);
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });
        panelMobil1.add(btnSearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 90, 30));

        kGradientPanel1.add(panelMobil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 370, 290));

        panelMobil3.setBackground(new java.awt.Color(0, 71, 67));
        panelMobil3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Tentukan Kriteria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelMobil3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "1", "2", "3", "4", "5" }));
        cTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTahunActionPerformed(evt);
            }
        });
        panelMobil3.add(cTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        jLabel26.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(249, 188, 97));
        jLabel26.setText("Tahun");
        panelMobil3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cHarga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "1", "2", "3", "4", "5" }));
        cHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHargaActionPerformed(evt);
            }
        });
        panelMobil3.add(cHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 80, -1));

        jLabel27.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(249, 188, 97));
        jLabel27.setText("Harga");
        panelMobil3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel28.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(249, 188, 97));
        jLabel28.setText("Jumlah Penumpang");
        panelMobil3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        cPenumpang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "1", "2", "3", "4" }));
        cPenumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPenumpangActionPerformed(evt);
            }
        });
        panelMobil3.add(cPenumpang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 80, -1));

        jLabel29.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(249, 188, 97));
        jLabel29.setText("Kapasitas Mesin");
        panelMobil3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        cMesin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "1", "2", "3", "4", "5" }));
        cMesin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMesinActionPerformed(evt);
            }
        });
        panelMobil3.add(cMesin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 80, -1));

        jLabel30.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(249, 188, 97));
        jLabel30.setText("Konsumsi Bbm");
        panelMobil3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        cBbm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "1", "2", "3", "4", "5" }));
        cBbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBbmActionPerformed(evt);
            }
        });
        panelMobil3.add(cBbm, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 80, -1));

        jLabel31.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(249, 188, 97));
        jLabel31.setText("Kecepatan Maksimum");
        panelMobil3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        cKecepatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "1", "2", "3", "4", "5" }));
        cKecepatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cKecepatanActionPerformed(evt);
            }
        });
        panelMobil3.add(cKecepatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 80, -1));

        kGradientPanel1.add(panelMobil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 830, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bgkayu.jpg"))); // NOI18N
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 780));

        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 749));
    }// </editor-fold>//GEN-END:initComponents

    private void tKecepatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKecepatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tKecepatanActionPerformed

    private void tMesinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMesinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMesinActionPerformed

    private void tBbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBbmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBbmActionPerformed

    private void tPenumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPenumpangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPenumpangActionPerformed

    private void tNoPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNoPlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNoPlatActionPerformed

    private void tMerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMerkActionPerformed

    private void tTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTypeActionPerformed

    private void tTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTahunActionPerformed

    private void tHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tHargaActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try{
            String sql = "UPDATE mobil SET merk=?,type=?,transmisi=?,tahun=?,jumlah_penumpang=?,konsumsi_bbm=?,kekuatan_mesin=?,kecepatan_maksimum=?,harga=?,status=? WHERE no_plat=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1,tMerk.getText());
            stat.setString(2,tType.getText());
            String transmisi="";
            if(rt1.isSelected()) transmisi="Automatic";
            else transmisi="Manual";
            stat.setString(3, transmisi);
            stat.setString(4,tTahun.getText());
            stat.setString(5,tPenumpang.getText());
            stat.setString(6,tBbm.getText());
            stat.setString(7,tMesin.getText());
            stat.setString(8,tKecepatan.getText());
            stat.setString(9,tHarga.getText());
            stat.setString(10,cStatus.getSelectedItem().toString());
            stat.setString(11,tNoPlat.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            kosong();
            tNoPlat.requestFocus();
            datatable();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
        }
    }//GEN-LAST:event_btnEditActionPerformed
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int ok = JOptionPane.showConfirmDialog(null,"Hapus ?","Konfirasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok==0){
            String sql="DELETE FROM mobil WHERE no_plat='"+tNoPlat.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");
                kosong();
                tNoPlat.requestFocus();
                datatable();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Data Gagal Dihapus"+e);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String sql = "INSERT INTO mobil VALUES(?,?,?,?,?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tNoPlat.getText());
            stat.setString(2, tMerk.getText());
            stat.setString(3, tType.getText());
            stat.setString(4, tTahun.getText());
            stat.setString(5, tPenumpang.getText());
            stat.setString(6, tMesin.getText());
            stat.setString(7, tBbm.getText());
            stat.setString(8, tKecepatan.getText());
            String transmisi="";
            if(rt1.isSelected()) transmisi="Automatic";
            else transmisi="Manual";
            stat.setString(9, transmisi);
            stat.setString(10, tHarga.getText());
            stat.setString(11, cStatus.getSelectedItem().toString());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            tNoPlat.requestFocus();
            datatable();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        kosong();
    }//GEN-LAST:event_btnClearActionPerformed
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String cari = tCari.getText();
        if(cari.equals("")){
            datacari();
        }else{
            datatable();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCariActionPerformed
    private void tabelMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMobilMouseClicked
        int bar = tabelMobil.getSelectedRow();
        String a = tabmode.getValueAt(bar,1).toString();
        String b = tabmode.getValueAt(bar,2).toString();
        String c = tabmode.getValueAt(bar,3).toString();
        String d = tabmode.getValueAt(bar,4).toString();
        String e = tabmode.getValueAt(bar,5).toString();
        String f = tabmode.getValueAt(bar,6).toString();
        String g = tabmode.getValueAt(bar,7).toString();
        String h = tabmode.getValueAt(bar,8).toString();
        String i = tabmode.getValueAt(bar,9).toString();
        String j = tabmode.getValueAt(bar,10).toString();
        String k = tabmode.getValueAt(bar,11).toString();
        tNoPlat.setText(a);
        tMerk.setText(b);
        tType.setText(c);
        String transmisi="Automatic";
        if(transmisi.equals(d)) rt1.setSelected(true);
        else rt2.setSelected(true);
        cStatus.setSelectedItem(e);
        tTahun.setText(f);
        tHarga.setText(g);
        tPenumpang.setText(h);
        tMesin.setText(i);
        tBbm.setText(j);
        tKecepatan.setText(k);
    }//GEN-LAST:event_tabelMobilMouseClicked
    private void cTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTahunActionPerformed
        String pilih = cTahun.getSelectedItem().toString();
        switch (pilih){
            case"1":
            tTahun1.setText("Sebelum Tahun 2013");
            kTahun="0 AND 2013";
            break;
            case"2":
            tTahun1.setText("Tahun 2013 Sampai 2015");
            kTahun="2014 AND 2015";
            break;
            case"3":
            tTahun1.setText("Tahun 2016 Sampai 2018");
            kTahun="2016 AND 2018";
            break;
            case"4":
            tTahun1.setText("Tahun 2019 Sampai 2022");
            kTahun="2019 AND 2022";
            break;
            case"5":
            tTahun1.setText("Tahun 2023");
            kTahun="2023 AND 9999";
            break;
            default:
            tTahun1.setText("");
            kTahun="0 AND 9999";
        }
    }//GEN-LAST:event_cTahunActionPerformed
    private void cHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHargaActionPerformed
        String pilih = cHarga.getSelectedItem().toString();
        switch (pilih){
            case"1":
            tHarga1.setText("Lebih dari Rp. 1.500.000");
            kHarga="1500000 AND 99999999";
            break;
            case"2":
            tHarga1.setText("Rp. 1.000.000 Sampai Rp. 1.500.000");
            kHarga="1000000 AND 1499999";
            break;
            case"3":
            tHarga1.setText("Rp. 700.000 Sampai kurang dari Rp. 1.000.000");
            kHarga=">=700000 AND 999999";
            break;
            case"4":
            tHarga1.setText("Rp. 500.000 Sampai kurang dari Rp. 700.000");
            kHarga="500000 AND 699999";
            System.out.println(kHarga);
            break;
            case"5":
            tHarga1.setText("Dibawah Rp. 500.000");
            kHarga="0 AND 499999";
            break;
            default:
            tHarga1.setText("");
            kHarga="0 AND 99999999";
        }
    }//GEN-LAST:event_cHargaActionPerformed
    private void cPenumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPenumpangActionPerformed
        String pilih = cPenumpang.getSelectedItem().toString();
        switch (pilih){
            case"1":
            tPenumpang1.setText("2 Kursi");
            kPenumpang="0 AND 2";
            break;
            case"2":
            tPenumpang1.setText("Lebih dari 2 kursi sampai 5 kursi");
            kPenumpang="3 AND 5";
            break;
            case"3":
            tPenumpang1.setText("Lebih dari 5 kursi sampai 8 kursi");
            kPenumpang="6 AND 8";
            break;
            case"4":
            tPenumpang1.setText("Lebih dari 8 kursi");
            kPenumpang="9 AND 99";
            break;
            default:
            tPenumpang1.setText("");
            kPenumpang="0 AND 99";
        }
    }//GEN-LAST:event_cPenumpangActionPerformed
    private void cMesinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMesinActionPerformed
        String pilih = cMesin.getSelectedItem().toString();
        switch (pilih){
            case"1":
            tMesin1.setText("Kurang dari 1000 cc");
            kMesin="0 AND 999";
            break;
            case"2":
            tMesin1.setText("1000 cc sampai 1300 cc");
            kMesin="1000 AND 1300";
            break;
            case"3":
            tMesin1.setText("Lebih dari 1300 cc sampai 1500 cc");
            kMesin="1301 AND 1500";
            break;
            case"4":
            tMesin1.setText("Lebih dari 1500 cc sampai 2000 cc");
            kMesin="1501 AND 2000";
            break;
            case"5":
            tMesin1.setText("Lebih dari 2000 cc");
            kMesin="2001 AND 9999";
            break;
            default:
            tMesin1.setText("");
            kMesin="0 AND 9999";
        }
    }//GEN-LAST:event_cMesinActionPerformed
    private void cBbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBbmActionPerformed
        String pilih = cBbm.getSelectedItem().toString();
        switch (pilih){
            case"1":
            tBbm1.setText("Kurang dari 10km/l");
            kBbm="0 AND 9";
            break;
            case"2":
            tBbm1.setText("10 km/l sampai kurang dari 13 km/l");
            kBbm="10 AND 12";
            break;
            case"3":
            tBbm1.setText("13 km/l sampai kurang dari 15 km/l");
            kBbm="13 AND 14";
            break;
            case"4":
            tBbm1.setText("15 km/l sampai 19 km/l");
            kBbm="15 AND 18";
            break;
            case"5":
            tBbm1.setText("lebih dari 19 km/l");
            kBbm="19 AND 99";
            break;
            default:
            tBbm1.setText("");
            kBbm="0 AND 99";
        }
    }//GEN-LAST:event_cBbmActionPerformed
    private void cKecepatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cKecepatanActionPerformed
        String pilih = cKecepatan.getSelectedItem().toString();
        switch (pilih){
            case"0":
            tKecepatan1.setText("");
            kKec="0 AND 999";
            break;
            case"1":
            tKecepatan1.setText("Kurang dari 100 km/j");
            kKec="0 AND 99";
            break;
            case"2":
            tKecepatan1.setText("100 km/j sampai kurang dari 150 km/j");
            kKec="100 AND 149";
            break;
            case"3":
            tKecepatan1.setText("150 km/j sampai kurang dari 180 km/j");
            kKec="150 AND 179";
            break;
            case"4":
            tKecepatan1.setText("180 km/j sampai 200 km/j");
            kKec="180 AND 200";
            break;
            case"5":
            tKecepatan1.setText("lebih dari 200 km/j");
            kKec="200 AND 999";
            break;
            default:
            tKecepatan1.setText("");
            kKec="0 AND 999";
        }
    }//GEN-LAST:event_cKecepatanActionPerformed
    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        FormKriteria fk = new FormKriteria();
        fk.setVisible(true);
    }//GEN-LAST:event_btnSearch2ActionPerformed
    int ii;
    static String kTahun,kHarga,kPenumpang,kMesin,kBbm,kKec;
    protected void datacari(){
        Object[] Baris={"No","Plat Nomor", "Merk", "Type", "Transmisi", "Status", "Tahun", "Harga", "Jumlah Penumpang", "Kekuatan Mesin", "Konsumsi Bbm", "Kecepatan Maksimum"};
        tabmode = new DefaultTableModel(null,Baris);
        tabelMobil.setModel(tabmode);
        String sql="SELECT * from mobil WHERE (harga BETWEEN "+kHarga+ ") AND (tahun BETWEEN "+kTahun+ ") AND (jumlah_penumpang BETWEEN "+kPenumpang+ ") AND (kekuatan_mesin BETWEEN "+kMesin+") AND (konsumsi_bbm BETWEEN "+kBbm+") ORDER BY preferensi DESC";
        System.out.println(kHarga);
        try{
            java.sql.Statement stat=conn.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            ii=1;
            while(hasil.next()){
                String a=hasil.getString("no_plat");
                String b=hasil.getString("merk");
                String c=hasil.getString("type");
                String d=hasil.getString("transmisi");
                String e=hasil.getString("status");
                String f=hasil.getString("tahun");
                String g=hasil.getString("harga");
                String h=hasil.getString("jumlah_penumpang");
                String i=hasil.getString("kekuatan_mesin");
                String j=hasil.getString("konsumsi_bbm");
                String k=hasil.getString("kecepatan_maksimum");
                String no=String.valueOf(ii);
                String[] data={no,a,b,c,d,e,f,g,h,i,j,k};
                tabmode.addRow(data);
                ii=ii+1;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Tidak Bisa Menampilkan Mobil Terbaik "+e);
        }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrupBbm;
    private javax.swing.ButtonGroup bgrupTransmisi;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JComboBox<String> cBbm;
    private javax.swing.JComboBox<String> cHarga;
    private javax.swing.JComboBox<String> cKecepatan;
    private javax.swing.JComboBox<String> cMesin;
    private javax.swing.JComboBox<String> cPenumpang;
    private javax.swing.JComboBox<String> cStatus;
    private javax.swing.JComboBox<String> cTahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPanel panelMobil;
    private javax.swing.JPanel panelMobil1;
    private javax.swing.JPanel panelMobil2;
    private javax.swing.JPanel panelMobil3;
    private javax.swing.JRadioButton rt1;
    private javax.swing.JRadioButton rt2;
    private javax.swing.JTextField tBbm;
    private javax.swing.JLabel tBbm1;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tHarga;
    private javax.swing.JLabel tHarga1;
    private javax.swing.JTextField tKecepatan;
    private javax.swing.JLabel tKecepatan1;
    private javax.swing.JTextField tMerk;
    private javax.swing.JTextField tMesin;
    private javax.swing.JLabel tMesin1;
    private javax.swing.JTextField tNoPlat;
    private javax.swing.JTextField tPenumpang;
    private javax.swing.JLabel tPenumpang1;
    private javax.swing.JTextField tTahun;
    private javax.swing.JLabel tTahun1;
    private javax.swing.JLabel tTahun10;
    private javax.swing.JLabel tTahun11;
    private javax.swing.JLabel tTahun12;
    private javax.swing.JLabel tTahun13;
    private javax.swing.JLabel tTahun2;
    private javax.swing.JLabel tTahun3;
    private javax.swing.JLabel tTahun4;
    private javax.swing.JLabel tTahun5;
    private javax.swing.JLabel tTahun6;
    private javax.swing.JLabel tTahun7;
    private javax.swing.JLabel tTahun8;
    private javax.swing.JLabel tTahun9;
    private javax.swing.JTextField tType;
    private javax.swing.JTable tabelMobil;
    // End of variables declaration//GEN-END:variables
}
