/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import java.io.File;
import java.sql.*;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author One For All
 */
public class FormPengembalian extends javax.swing.JPanel {
    private final Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    PreparedStatement pStat;
    String a,b,c,d,e,f,g,h,i,j,k,l,m,n,o;
    String pinjam,kembali;
    public FormPengembalian() {
        initComponents();
        Locale locale = new Locale("id","ID");
        Locale.setDefault(locale);
        datatable();
        dataTransaksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        tCari = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnFinish = new javax.swing.JButton();
        tTotal = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tBayar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tSisa = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        PanelDataPelanggan = new javax.swing.JPanel();
        tNik = new javax.swing.JLabel();
        tNama = new javax.swing.JLabel();
        cTransaksi = new javax.swing.JComboBox<>();
        tLama = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tDenda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tOvertime = new javax.swing.JTextField();
        tBiayaOvertime = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tType = new javax.swing.JLabel();
        tNoPlat = new javax.swing.JLabel();
        tHarga = new javax.swing.JLabel();
        tJasa = new javax.swing.JLabel();
        tTglPinjam = new javax.swing.JLabel();
        tTglKembali = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tIdTransaksi = new javax.swing.JTextField();
        tId = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(1330, 800));
        setPreferredSize(new java.awt.Dimension(1330, 800));

        kGradientPanel2.setkEndColor(new java.awt.Color(98, 215, 196));
        kGradientPanel2.setkGradientFocus(2000);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 87, 64));
        kGradientPanel2.setMinimumSize(new java.awt.Dimension(100, 300));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelTransaksi.setBackground(new java.awt.Color(1, 135, 100));
        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);

        kGradientPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 1200, 270));

        tCari.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        tCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCariActionPerformed(evt);
            }
        });
        kGradientPanel2.add(tCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 160, 30));

        jPanel2.setBackground(new java.awt.Color(0, 71, 67));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Pinjam Mobil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDelete.setFont(new java.awt.Font("Eras Demi ITC", 1, 11)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trash.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setInheritsPopupMenu(true);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 100, 30));

        btnClear.setFont(new java.awt.Font("Eras Demi ITC", 1, 11)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh26.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.setInheritsPopupMenu(true);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 100, 30));

        btnEdit.setFont(new java.awt.Font("Eras Demi ITC", 1, 11)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit_f2.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setInheritsPopupMenu(true);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel2.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 100, 30));

        btnFinish.setFont(new java.awt.Font("Eras Demi ITC", 1, 11)); // NOI18N
        btnFinish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/save-16x16i.png"))); // NOI18N
        btnFinish.setText("Finish");
        btnFinish.setInheritsPopupMenu(true);
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });
        jPanel2.add(btnFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, 30));

        tTotal.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tTotal.setForeground(new java.awt.Color(249, 188, 97));
        tTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(tTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 110, 20));

        jLabel18.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(249, 188, 97));
        jLabel18.setText("Sisa");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        tBayar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tBayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBayarActionPerformed(evt);
            }
        });
        jPanel2.add(tBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 110, -1));

        jLabel19.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(249, 188, 97));
        jLabel19.setText("Bayar");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel17.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(249, 188, 97));
        jLabel17.setText("Lama Peminjaman");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jLabel21.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(249, 188, 97));
        jLabel21.setText("Total Bayar");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        tSisa.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tSisa.setForeground(new java.awt.Color(249, 188, 97));
        tSisa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(tSisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 110, 20));

        jLabel44.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(249, 188, 97));
        jLabel44.setText(":");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 10, -1));

        jLabel45.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(249, 188, 97));
        jLabel45.setText(":");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 10, -1));

        jLabel46.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(249, 188, 97));
        jLabel46.setText(":");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 10, -1));

        jLabel47.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(249, 188, 97));
        jLabel47.setText(":");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 10, -1));

        jLabel48.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(249, 188, 97));
        jLabel48.setText(":");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 10, -1));

        btnPrint.setFont(new java.awt.Font("Eras Demi ITC", 1, 11)); // NOI18N
        btnPrint.setIcon(new javax.swing.ImageIcon("C:\\Users\\bamba\\Downloads\\icons8-print-36.png")); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setInheritsPopupMenu(true);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 110, 30));

        kGradientPanel2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 370, 320, 320));

        btnSearch.setFont(new java.awt.Font("Eras Demi ITC", 1, 11)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cari.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setInheritsPopupMenu(true);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 100, 30));

        PanelDataPelanggan.setBackground(new java.awt.Color(0, 71, 67));
        PanelDataPelanggan.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Data Pelanggan & Mobil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        PanelDataPelanggan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tNik.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tNik.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tNik, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 170, 20));

        tNama.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tNama.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, 20));

        cTransaksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --" }));
        cTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTransaksiActionPerformed(evt);
            }
        });
        PanelDataPelanggan.add(cTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 170, -1));

        tLama.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tLama.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tLama, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 20, 20));

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 188, 97));
        jLabel1.setText("Jasa Supir");
        PanelDataPelanggan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(249, 188, 97));
        jLabel13.setText("No Transaksi");
        PanelDataPelanggan.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(249, 188, 97));
        jLabel11.setText("Tgl Peminjaman");
        PanelDataPelanggan.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(249, 188, 97));
        jLabel12.setText("Tgl Pengembalian");
        PanelDataPelanggan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        jLabel14.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(249, 188, 97));
        jLabel14.setText("Lama Peminjaman");
        PanelDataPelanggan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(249, 188, 97));
        jLabel15.setText("Hari");
        PanelDataPelanggan.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 39, -1));

        tDenda.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tDenda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDendaActionPerformed(evt);
            }
        });
        PanelDataPelanggan.add(tDenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 110, -1));

        jLabel6.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(249, 188, 97));
        jLabel6.setText("Plat Nomor");
        PanelDataPelanggan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel22.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(249, 188, 97));
        jLabel22.setText("Denda");
        PanelDataPelanggan.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        jLabel23.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(249, 188, 97));
        jLabel23.setText("Biaya Overtime");
        PanelDataPelanggan.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        tOvertime.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tOvertime.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tOvertime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tOvertimeActionPerformed(evt);
            }
        });
        PanelDataPelanggan.add(tOvertime, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 30, -1));

        tBiayaOvertime.setEditable(false);
        tBiayaOvertime.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tBiayaOvertime.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tBiayaOvertime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBiayaOvertimeActionPerformed(evt);
            }
        });
        PanelDataPelanggan.add(tBiayaOvertime, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 110, -1));

        jLabel24.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(249, 188, 97));
        jLabel24.setText("Overtime");
        PanelDataPelanggan.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        btnHitung.setFont(new java.awt.Font("Eras Demi ITC", 1, 11)); // NOI18N
        btnHitung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/save-16x16i.png"))); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.setInheritsPopupMenu(true);
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        PanelDataPelanggan.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 100, 30));

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 188, 97));
        jLabel2.setText("Harga");
        PanelDataPelanggan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel31.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(249, 188, 97));
        jLabel31.setText(":");
        PanelDataPelanggan.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 10, -1));

        jLabel32.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(249, 188, 97));
        jLabel32.setText(":");
        PanelDataPelanggan.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 10, -1));

        jLabel33.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(249, 188, 97));
        jLabel33.setText(":");
        PanelDataPelanggan.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 10, -1));

        jLabel34.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(249, 188, 97));
        jLabel34.setText(":");
        PanelDataPelanggan.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 10, -1));

        jLabel35.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(249, 188, 97));
        jLabel35.setText(":");
        PanelDataPelanggan.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 10, -1));

        jLabel36.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(249, 188, 97));
        jLabel36.setText(":");
        PanelDataPelanggan.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 10, -1));

        jLabel37.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(249, 188, 97));
        jLabel37.setText(":");
        PanelDataPelanggan.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 10, -1));

        jLabel38.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(249, 188, 97));
        jLabel38.setText(":");
        PanelDataPelanggan.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 10, -1));

        jLabel39.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(249, 188, 97));
        jLabel39.setText(":");
        PanelDataPelanggan.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 10, -1));

        jLabel40.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(249, 188, 97));
        jLabel40.setText(":");
        PanelDataPelanggan.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 10, -1));

        jLabel41.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(249, 188, 97));
        jLabel41.setText(":");
        PanelDataPelanggan.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 10, -1));

        jLabel42.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(249, 188, 97));
        jLabel42.setText(":");
        PanelDataPelanggan.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 10, -1));

        jLabel43.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(249, 188, 97));
        jLabel43.setText(":");
        PanelDataPelanggan.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 10, -1));

        jLabel7.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(249, 188, 97));
        jLabel7.setText("NIK");
        PanelDataPelanggan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel16.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(249, 188, 97));
        jLabel16.setText("Nama Pelanggan");
        PanelDataPelanggan.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(249, 188, 97));
        jLabel8.setText("Type Mobil");
        PanelDataPelanggan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        tType.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tType.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tType, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 170, 20));

        tNoPlat.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tNoPlat.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tNoPlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 170, 20));

        tHarga.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tHarga.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 170, 20));

        tJasa.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tJasa.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 170, 20));

        tTglPinjam.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tTglPinjam.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tTglPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 130, 20));

        tTglKembali.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        tTglKembali.setForeground(new java.awt.Color(249, 188, 97));
        PanelDataPelanggan.add(tTglKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 130, 20));

        kGradientPanel2.add(PanelDataPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 820, 320));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bgkayu.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        kGradientPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 800));

        tIdTransaksi.setEditable(false);
        tIdTransaksi.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tIdTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdTransaksiActionPerformed(evt);
            }
        });
        kGradientPanel2.add(tIdTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 170, -1));

        tId.setEditable(false);
        tId.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdActionPerformed(evt);
            }
        });
        kGradientPanel2.add(tId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1330, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

     protected void kosong(){
        tIdTransaksi.setText("");
        tNik.setText("");
        tNama.setText("");
        tType.setText("");
        tNoPlat.setText("");
        tJasa.setText("");
        tHarga.setText("");
        tTglPinjam.setText("");
        tTglKembali.setText("");
        tLama.setText("");
        tDenda.setText("");
        tOvertime.setText("");
        tBiayaOvertime.setText("");
        tTotal.setText("");
        tBayar.setText("");
        tSisa.setText("");
        cTransaksi.setSelectedIndex(0);
    }
    
    protected void datatable(){
        Object[] Baris={"id_transaksi", "Nama Pelanggan", "Plat Nomor", "Harga", "Tanggal Pinjam", "Tanggal Kembail","Lama Sewa", "Overtime", "Denda", "Bayar", "Total Bayar", "Status Transaksi"};
        tabmode = new DefaultTableModel(null,Baris);
        tabelTransaksi.setModel(tabmode);
        String sql="SELECT * from pinjam INNER JOIN pelanggan ON pelanggan.nik = pinjam.nik INNER JOIN mobil ON mobil.no_plat=pinjam.no_plat WHERE status_transaksi='Selesai' AND (id_transaksi LIKE '%"+tCari.getText()+"%'"
                + "OR pinjam.nik LIKE '%"+tCari.getText()+"%' "
                + "OR nama LIKE '%"+tCari.getText()+"%' "
                + "OR pinjam.no_plat LIKE '%"+tCari.getText()+"%' "
                + "OR type LIKE '%"+tCari.getText()+"%' "
                + "OR harga LIKE '%"+tCari.getText()+"%' "
                + "OR tgl_pinjam LIKE '%"+tCari.getText()+"%' "
                + "OR tgl_kembali LIKE '%"+tCari.getText()+"%' "
                + "OR lama_pinjam LIKE '%"+tCari.getText()+"%' "
                + "OR id_supir LIKE '%"+tCari.getText()+"%' "
                + "OR overtime LIKE '%"+tCari.getText()+"%' "
                + "OR total LIKE '%"+tCari.getText()+"%' "
                + "OR bayar LIKE '%"+tCari.getText()+"%' )";
        try{
            java.sql.Statement stat=conn.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                a=hasil.getString("id_transaksi");
                b=hasil.getString("nama");
                c=hasil.getString("no_Plat");
                d=hasil.getString("harga");
                e=hasil.getString("tgl_pinjam");
                f=hasil.getString("tgl_kembali");
                g=hasil.getString("lama_pinjam");
                h=hasil.getString("overtime");
                i=hasil.getString("denda");
                j=hasil.getString("bayar");
                k=hasil.getString("total");
                l=hasil.getString("status_transaksi");
                String[] data={a,b,c,d,e,f,g,h,i,j,k,l};
                tabmode.addRow(data);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Tidak Bisa Menampilkan Tabel "+e);
        }
    }
    
    protected void dataTransaksi(){
        String sql = "SELECT * FROM pinjam WHERE status_transaksi='Berjalan'";
        try{
            java.sql.Statement stat=conn.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                a = hasil.getString("id_transaksi");
                cTransaksi.addItem(a);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Data Transaksi Tidak Tampil "+e);
        }
    }
    
    public void isiField(){
        String sql = "SELECT * FROM pinjam INNER JOIN pelanggan ON pelanggan.nik = pinjam.nik INNER JOIN mobil ON mobil.no_plat = pinjam.no_plat WHERE id_transaksi='"+cTransaksi.getSelectedItem().toString()+"'";
        try{
            java.sql.Statement stat=conn.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                a=hasil.getString("nik");
                b=hasil.getString("nama");
                c=hasil.getString("no_plat");
                d=hasil.getString("harga");
                e=hasil.getString("tgl_pinjam");
                f=hasil.getString("tgl_kembali");
                g=hasil.getString("lama_pinjam");
                h=hasil.getString("total");
                i=hasil.getString("bayar");
                j=hasil.getString("type");
                k=hasil.getString("id_supir");
                if(k.equals("Tanpa Supir")){
                    tJasa.setText("");
                }else{
                    String sql2 = "SELECT * FROM supir WHERE id_supir='"+k+"'";
                try{
                    java.sql.Statement stat2=conn.createStatement();
                    ResultSet hasil2=stat.executeQuery(sql2);
                    while(hasil2.next()){
                        l = hasil2.getString("biaya");
                        tJasa.setText(l);
                    }
                }catch(Exception e){
                    System.out.println("Data Supir Tidak Tampil "+e);
                }
                }
                tNik.setText(a);
                tNama.setText(b);
                tNoPlat.setText(c);
                tHarga.setText(d);
                tTglPinjam.setText(e);
                tTglKembali.setText(f);
                tLama.setText(g);
                tTotal.setText(h);
                tBayar.setText(i);
                tType.setText(j);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void hitung(){
            int hrg = Integer.valueOf(tHarga.getText());
            int dpp = Integer.valueOf(tBayar.getText());
            int ovtt;
            if (tOvertime.getText().equals("")){
                ovtt = 0;
                tOvertime.setText(String.valueOf(ovtt));
            }else{
                ovtt = Integer.valueOf(tOvertime.getText());
            }
            int lama = Integer.valueOf(tLama.getText());
            int denda;
            if (tDenda.getText().equals("")){
                denda = 0;
            }else{
                denda = Integer.valueOf(tDenda.getText());
            }
            int supir;
            if(tJasa.getText().equals("")){
                supir = 0;
            }else{
                supir = Integer.valueOf(tJasa.getText());
            }
            int hovt = (int) (0.10 * (hrg+supir) * ovtt);
            int hargas = (hrg+supir) * lama;
            tBiayaOvertime.setText(String.valueOf(hovt));
            int total = hovt + hargas + denda;
            tTotal.setText(String.valueOf(total));
            int sisa = total - dpp;
            tSisa.setText(String.valueOf(sisa));
    }
    
    private void bayarMobil(){
        String sql = "UPDATE pinjam SET total=?, bayar=?, overtime=?, denda=?, status_transaksi='Selesai' WHERE id_transaksi='"+cTransaksi.getSelectedItem().toString()+"'";
        try {
                pStat = conn.prepareStatement(sql);
                pStat.setString(1,tTotal.getText());
                String bayar = tBayar.getText();
                System.out.println("bayar mobil"+bayar);
                pStat.setString(2,bayar);
                pStat.setString(3,tOvertime.getText());
                int denda;
                if (tDenda.getText().equals("")){
                    denda = 0;
                }else{
                    denda = Integer.valueOf(tDenda.getText());
                }
                pStat.setString(4,String.valueOf(denda));
                pStat.executeUpdate();
                String sql2 = "UPDATE mobil SET status='Tersedia' WHERE no_plat='"+tNoPlat.getText()+"'";
                PreparedStatement pStat2 = conn.prepareStatement(sql2);
                pStat2.executeUpdate();
                JOptionPane.showMessageDialog(null, "Transaksi Penyewaan Selesai");
                kosong();
                datatable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e);
        }
    }
    private void ubah(){
        String sql = "UPDATE pinjam SET total=?, bayar=?, overtime=?, denda=? WHERE id_transaksi='"+tIdTransaksi.getText()+"'";
        try {
            pStat = conn.prepareStatement(sql);
            pStat.setString(1, tTotal.getText());
            String bayar = tBayar.getText();
            System.out.println("ubah bayaran mobil"+bayar);
            pStat.setString(2,bayar);
            pStat.setString(3, tOvertime.getText());
            pStat.setString(4, tDenda.getText());
            pStat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            kosong();
            cTransaksi.requestFocus();
            datatable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal diubah" + e);
        }
    }
    private void hapus(){
        int ok = JOptionPane.showConfirmDialog(null,"Hapus ?","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok==0){
            String sql="DELETE FROM pinjam WHERE id_transaksi='"+tIdTransaksi.getText()+"'";
            try{
                System.out.println(tIdTransaksi.getText());
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");
                kosong();
                cTransaksi.requestFocus();
                datatable();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Data Gagal Dihapus"+e);
            }
        }
    }

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        datatable();
    }//GEN-LAST:event_btnSearchActionPerformed
    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        hitung();
    }//GEN-LAST:event_btnHitungActionPerformed
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        ubah();
    }//GEN-LAST:event_btnEditActionPerformed
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        kosong();
    }//GEN-LAST:event_btnClearActionPerformed
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        hapus();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCariActionPerformed

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
        int bar = tabelTransaksi.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        tIdTransaksi.setText(a);
        String sql = "SELECT * FROM pinjam INNER JOIN pelanggan ON pelanggan.nik=pinjam.nik INNER JOIN mobil ON mobil.no_plat=pinjam.no_plat WHERE id_transaksi='"+a+"'";
        try {
            java.sql.Statement cStat= conn.createStatement();
            ResultSet hasil = cStat.executeQuery(sql);
            while(hasil.next()){
                b = hasil.getString("nik");
                c = hasil.getString("nama");
                d = hasil.getString("type");
                e = hasil.getString("harga");
                f = hasil.getString("tgl_pinjam");
                g = hasil.getString("tgl_kembali");
                h = hasil.getString("lama_pinjam");
                i = hasil.getString("total");
                j = hasil.getString("overtime");
                k = hasil.getString("denda");
                l = hasil.getString("bayar");
                m = hasil.getString("no_plat");
                n = hasil.getString("id_supir");
                if(n.equals("Tanpa Supir")){
                    tJasa.setText("");
                }else{
                    String sql2 = "SELECT * FROM supir WHERE id_supir='"+n+"'";
                    try{
                        java.sql.Statement stat2=conn.createStatement();
                        ResultSet hasil2=stat2.executeQuery(sql2);
                        while(hasil2.next()){
                            n = hasil2.getString("biaya");
                            tJasa.setText(n);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,e.getMessage());
                    }
                }
                int total = Integer.valueOf(i);
                int harga = Integer.valueOf(e);
                int overtime = Integer.valueOf(j);
                int lama = Integer.valueOf(h);
                int denda = Integer.valueOf(k);
                int bayar = Integer.valueOf(l);
                int hargatotal = harga * lama;
                System.out.println(hargatotal);
                System.out.println(total);
                if(j.equals("0")){
                    tBiayaOvertime.setText("");
                }else{
                    int hargaOvertime = total - hargatotal - denda;
                    System.out.println(hargaOvertime);
                    tBiayaOvertime.setText(String.valueOf(hargaOvertime));
                }
                int sisa = total - bayar;
                tNik.setText(b);
                tNama.setText(c);
                tNoPlat.setText(m);
                tType.setText(d);
                tHarga.setText(e);
                tTglPinjam.setText(f);
                tTglKembali.setText(g);
                tLama.setText(h);
                tTotal.setText(i);
                tDenda.setText(k);
                tOvertime.setText(j);
                tBayar.setText(l);
                tSisa.setText(String.valueOf(sisa));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tabelTransaksiMouseClicked

    private void tIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdActionPerformed

    private void cTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTransaksiActionPerformed
        isiField();
    }//GEN-LAST:event_cTransaksiActionPerformed

    private void tBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBayarActionPerformed

    private void tDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDendaActionPerformed

    private void tOvertimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tOvertimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tOvertimeActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        bayarMobil();
    }//GEN-LAST:event_btnFinishActionPerformed

    private void tBiayaOvertimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBiayaOvertimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBiayaOvertimeActionPerformed

    private void tIdTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdTransaksiActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try{
            File file = new File("src/report/buktiPembayaran.jrxml");
            JasperDesign jasperDesign = JRXmlLoader.load(file);
            Map <String,Object> parham = new HashMap<>();
            parham.put("IdTransaksi", tIdTransaksi.getText());
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parham,conn);
            JasperViewer.viewReport(jasperPrint, false);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Tidak Bisa Cetak Bukti Pengembalian" + e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

   
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDataPelanggan;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField tBayar;
    private javax.swing.JTextField tBiayaOvertime;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tDenda;
    private javax.swing.JLabel tHarga;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tIdTransaksi;
    private javax.swing.JLabel tJasa;
    private javax.swing.JLabel tLama;
    private javax.swing.JLabel tNama;
    private javax.swing.JLabel tNik;
    private javax.swing.JLabel tNoPlat;
    private javax.swing.JTextField tOvertime;
    private javax.swing.JLabel tSisa;
    private javax.swing.JLabel tTglKembali;
    private javax.swing.JLabel tTglPinjam;
    private javax.swing.JLabel tTotal;
    private javax.swing.JLabel tType;
    private javax.swing.JTable tabelTransaksi;
    // End of variables declaration//GEN-END:variables

    private void setExtendedState(float CENTER_ALIGNMENT) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
