/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author One For All
 */

public class MainMenu extends javax.swing.JFrame {

    Form fr = new Form();

    
    /**
     * Creates new form MainMenu
     */
    int mousepX ;
    int mousepY ;
    boolean a=true;
    ImageIcon ii;
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        Icon = new javax.swing.JPanel();
        ButtonClose = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        ButtonMax = new javax.swing.JPanel();
        ButtonMin = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        MenuHide = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        LineLogout = new javax.swing.JPanel();
        Logout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        btnSupir = new javax.swing.JLabel();
        btnMobil = new javax.swing.JLabel();
        btnPinjam = new javax.swing.JLabel();
        btnLaporan = new javax.swing.JLabel();
        BtnPelanggan = new javax.swing.JLabel();
        Customer4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(1, 135, 100));
        Header.setPreferredSize(new java.awt.Dimension(800, 35));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new java.awt.BorderLayout());

        Icon.setBackground(new java.awt.Color(0, 0, 255));
        Icon.setPreferredSize(new java.awt.Dimension(120, 50));
        Icon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonClose.setBackground(new java.awt.Color(1, 135, 100));
        ButtonClose.setPreferredSize(new java.awt.Dimension(40, 35));
        ButtonClose.setLayout(new java.awt.BorderLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/close-24.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        ButtonClose.add(close, java.awt.BorderLayout.CENTER);

        Icon.add(ButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        ButtonMax.setBackground(new java.awt.Color(1, 135, 100));
        ButtonMax.setPreferredSize(new java.awt.Dimension(40, 35));
        ButtonMax.setLayout(new java.awt.BorderLayout());
        Icon.add(ButtonMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ButtonMin.setBackground(new java.awt.Color(1, 135, 100));
        ButtonMin.setPreferredSize(new java.awt.Dimension(40, 35));
        ButtonMin.setLayout(new java.awt.BorderLayout());

        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Substract 24px.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        ButtonMin.add(minimize, java.awt.BorderLayout.CENTER);

        Icon.add(ButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        Header.add(Icon, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        menu.setBackground(new java.awt.Color(51, 51, 255));
        menu.setPreferredSize(new java.awt.Dimension(50, 450));
        menu.setLayout(new java.awt.BorderLayout());

        MenuHide.setBackground(new java.awt.Color(1, 71, 67));

        MenuIcon.setBackground(new java.awt.Color(1, 135, 100));
        MenuIcon.setPreferredSize(new java.awt.Dimension(50, 465));
        MenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LineLogout.setBackground(new java.awt.Color(1, 135, 100));
        LineLogout.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout LineLogoutLayout = new javax.swing.GroupLayout(LineLogout);
        LineLogout.setLayout(LineLogoutLayout);
        LineLogoutLayout.setHorizontalGroup(
            LineLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        LineLogoutLayout.setVerticalGroup(
            LineLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(LineLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, -1));

        Logout.setBackground(new java.awt.Color(1, 135, 100));
        Logout.setPreferredSize(new java.awt.Dimension(50, 50));
        Logout.setLayout(new java.awt.BorderLayout());
        MenuIcon.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, -1));

        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-shutdown-45.png"))); // NOI18N
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogoutMousePressed(evt);
            }
        });
        MenuIcon.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 50));

        javax.swing.GroupLayout MenuHideLayout = new javax.swing.GroupLayout(MenuHide);
        MenuHide.setLayout(MenuHideLayout);
        MenuHideLayout.setHorizontalGroup(
            MenuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuHideLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MenuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MenuHideLayout.setVerticalGroup(
            MenuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        menu.add(MenuHide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        kGradientPanel1.setkEndColor(new java.awt.Color(98, 215, 196));
        kGradientPanel1.setkGradientFocus(1300);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 87, 64));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSupir.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        btnSupir.setForeground(new java.awt.Color(249, 188, 97));
        btnSupir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-driver-66.png"))); // NOI18N
        btnSupir.setText("Supir");
        btnSupir.setToolTipText("");
        btnSupir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSupir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSupir.setIconTextGap(10);
        btnSupir.setVerifyInputWhenFocusTarget(false);
        btnSupir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSupir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupirMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnSupir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 112));

        btnMobil.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        btnMobil.setForeground(new java.awt.Color(249, 188, 97));
        btnMobil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cars-icon-72.png"))); // NOI18N
        btnMobil.setText("Mobil");
        btnMobil.setToolTipText("");
        btnMobil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMobil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMobil.setIconTextGap(10);
        btnMobil.setVerifyInputWhenFocusTarget(false);
        btnMobil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMobilMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, 112));

        btnPinjam.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        btnPinjam.setForeground(new java.awt.Color(249, 188, 97));
        btnPinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/loan.png"))); // NOI18N
        btnPinjam.setText("Pinjam Mobil");
        btnPinjam.setToolTipText("");
        btnPinjam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPinjam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPinjam.setIconTextGap(10);
        btnPinjam.setVerifyInputWhenFocusTarget(false);
        btnPinjam.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPinjamMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, 112));

        btnLaporan.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(249, 188, 97));
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/report (2).png"))); // NOI18N
        btnLaporan.setText("Laporan");
        btnLaporan.setToolTipText("");
        btnLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLaporan.setIconTextGap(10);
        btnLaporan.setVerifyInputWhenFocusTarget(false);
        btnLaporan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, 112));

        BtnPelanggan.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        BtnPelanggan.setForeground(new java.awt.Color(249, 188, 97));
        BtnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/customer-icon-72.png"))); // NOI18N
        BtnPelanggan.setText("Pelanggan");
        BtnPelanggan.setToolTipText("");
        BtnPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPelanggan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPelanggan.setIconTextGap(10);
        BtnPelanggan.setVerifyInputWhenFocusTarget(false);
        BtnPelanggan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPelangganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnPelangganMouseEntered(evt);
            }
        });
        kGradientPanel1.add(BtnPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 112));

        Customer4.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        Customer4.setForeground(new java.awt.Color(249, 188, 97));
        Customer4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/car-loan.png"))); // NOI18N
        Customer4.setText("Pengembalian");
        Customer4.setToolTipText("");
        Customer4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Customer4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Customer4.setIconTextGap(10);
        Customer4.setVerifyInputWhenFocusTarget(false);
        Customer4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kGradientPanel1.add(Customer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, 112));

        getContentPane().add(kGradientPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(800, 494));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
        if(numberbool == 1){
            h1.setBackground(new Color(1,71,67));
            h2.setBackground(new Color(1,135,100));
        }
        else{
            h1.setBackground(new Color(1,135,100));
            h2.setBackground(new Color(1,71,67));
        }
    }
    
    
    
    
    
    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int koordinatX = evt.getXOnScreen();
        int koordinatY = evt.getYOnScreen();    
        this.setLocation(koordinatX-mousepX, koordinatY-mousepY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void BtnPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPelangganMouseClicked
        // TODO add your handling code here:
        FormPelanggan fp = new FormPelanggan();
        fp.setVisible(true);
        fr.main_panel.removeAll();
        fr.main_panel.repaint();
        fr.main_panel.add(fp);
        fr.main_panel.revalidate();
        fr.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnPelangganMouseClicked

    private void btnLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMousePressed

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        changecolor(LineLogout, new Color(1,135,100));
    }//GEN-LAST:event_btnLogoutMouseExited
    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        changecolor(LineLogout, new Color(247, 2, 2));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        login log = new login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void BtnPelangganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPelangganMouseEntered
           setForeground(Color.WHITE);
    }//GEN-LAST:event_BtnPelangganMouseEntered

    private void btnMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMobilMouseClicked
        FormMobil fm = new FormMobil();
        fm.setVisible(true);
        fr.main_panel.removeAll();
        fr.main_panel.repaint();
        fr.main_panel.add(fm);
        fr.main_panel.revalidate();
        fr.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMobilMouseClicked

    private void btnPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPinjamMouseClicked
        FormTransaksi ft = new FormTransaksi();
        ft.setVisible(true);
        fr.main_panel.removeAll();
        fr.main_panel.repaint();
        fr.main_panel.add(ft);
        fr.main_panel.revalidate();
        fr.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPinjamMouseClicked

    private void btnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseClicked
        // TODO add your handling code here:
        FormLaporan fl = new FormLaporan();
        fl.setVisible(true);
    }//GEN-LAST:event_btnLaporanMouseClicked

    private void btnSupirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupirMouseClicked
        // TODO add your handling code here:
        FormSupir fs = new FormSupir();
        fs.setVisible(true);
    }//GEN-LAST:event_btnSupirMouseClicked

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        changecolor(ButtonMin, new Color(1,135,100));
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        changecolor(ButtonMin, new Color(100,135,100));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        changecolor(ButtonClose, new Color(1,135,100));
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        changecolor(ButtonClose, new Color(100,135,100));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnPelanggan;
    private javax.swing.JPanel ButtonClose;
    private javax.swing.JPanel ButtonMax;
    private javax.swing.JPanel ButtonMin;
    private javax.swing.JLabel Customer4;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Icon;
    private javax.swing.JPanel LineLogout;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel MenuHide;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JLabel btnLaporan;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnMobil;
    private javax.swing.JLabel btnPinjam;
    private javax.swing.JLabel btnSupir;
    private javax.swing.JLabel close;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel minimize;
    // End of variables declaration//GEN-END:variables
}
